### ISSUE TITLE
some images seems to have not correct url

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#10]
I don't know exactly when but it seems that some images, like gravatar default, havent' a correct link so they arent' shown.
Gravatar default image has an url like /img/anonymous_avatar.jpg and not /system/img/anonymous_avatar.jpg (like the logo one in frontend web site that shows properly).
I found the same problem on the admin login page, in this case with the logo image on the left side (/img/logo.png and not system/img/logo.png)

There is another probably small problem, in some pages (with debug setting > 0) on top of the frontend website i can see
"Notice (8): Undefined variable: SetSmileyURL [APP/Plugin/Comment/Model/Behavior/BBCodeBehavior.php, line 25]"
ie: in the "Hook Tags" page

I hope these are not problem derived by my modifications

**Comment by quickapps** [comment]
About images url,
Both problems are related to the commit: 1aa01c9675b2ad86a133541d30fb577f8c171bd6
- The `admin login` logo issue was fixed just yesterday here: 85084d3edbdd10836f876a1176342251d2d019a3
- The `/img/anonymous_avatar.jpg` issue: Well the default avatar image url is stored in DB, you can change it in the `Configuration` section (/admin/system/configuration). All installation `.sql` files were updated on 1aa01c9 to the correct value (`/system/img/anonymous_avatar.jpg`), so if you are using a previous install then you would have to apply this change manually as I described before.

Thanks!

**Comment by Gabri** [comment]
thank you very much
