### ISSUE TITLE
QuickApps-CMS 2.0 is not compatible with case-sensitive filesystems

### ISSUE THREAD

**Issue by SergeR** [quickapps/cms#100]
Many routes (and in-controller redirects) points to a lowercased class names. So autoloader cannot load the proper controller classes.

The code below causes an error 'Missing Controller. Error: Installer.startupController could not be found.'. The route `/installer/startup` doesn't work but `/installer/Startup` works fine

``` php
        Router::redirect(
                '/:anything_but_installer',
                ['plugin' => 'Installer', 'controller' => 'startup'],
                ['anything_but_installer' => '(?!installer).*', 'status' => 302]
        );

        Router::plugin('Installer', function($routes) {
                $routes->connect('/:controller', ['action' => 'index']);
                $routes->connect('/:controller/:action/*', []);
        });
```

**Comment by quickapps** [comment]
My bad, I thought that Cake 3.0 was keeping the inflection for controller names.
For example, in cake 2.0 "super_name" maps to "SuperNameController".

I'll take a look, thanks for helping ^^

**Comment by SergeR** [comment]
Since 5 Jul Cake 3 doesn't have a default routes (https://github.com/cakephp/cakephp/commit/a30f1c505c4a69bb4abb94d5b1d7aec1ffbd7015)

I hope that will help

``` php
Router::plugin('Installer', function($routes) {
                $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'Cake\Routing\Route\InflectedRoute']);
                $routes->connect('/:controller/:action/*', [], ['routeClass' => 'Cake\Routing\Route\InflectedRoute']);
        });
```

**Comment by quickapps** [comment]
Oh I see, Routing\RouterBuilder uses `Cake\Routing\Route\Route` as default "routeClass"..

Ye, you are right, I have to manually set 'Cake\Routing\Route\InflectedRoute' on every route
