### ISSUE TITLE
Delete Blocks?

### ISSUE THREAD

**Issue by ivanbochev** [quickapps/cms#106]
Is it possible to delete blocks under /admin/block, once created?

**Comment by quickapps** [comment]
Yes, you can only delete blocks that were created using the "Create New Block" button. There are some blocks (Widget blocks) such Menu Blocks that cannot be manually deleted.

![menu-delete](https://cloud.githubusercontent.com/assets/1129842/7299362/b069a6d0-e9d5-11e4-9b3e-ae6fdcbaa0a6.png)

**Comment by ivanbochev** [comment]
Thank you for your quick replies.

In my case it is a copied(duplicated) Menu Block, but I do not see a delete button.

**Comment by quickapps** [comment]
Oh I see,
Then I think it may be a bug or simply I forgot to include this feature, but I think copies should be deletable.

Marking as hold, I'll take a look to this.

**Comment by ivanbochev** [comment]
Many thanks :-)
