### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by ghost** [quickapps/cms#107]
Hello Web developers
I'm trying to install Quick Apps, and do not get along. Can I install this CMS via FTP? Unfortunately, I find no installer via FTP. I have also tried with Composer. It returns the same files are uploaded to the web space, which I uploaded via FTP.

But how can I install it? Happy about rapid response.

![quickapps-ftp-view](https://cloud.githubusercontent.com/assets/7885632/7866670/51c764f2-0571-11e5-876c-fa99b95fdc78.jpg)

**Comment by quickapps** [comment]
Hi Alex,

There is a installation tutorial right here: http://api.quickappscms.org/book/getting-started/installation.html#install-using-ftp

Your directory structure seems right. For FTP installation basically you have to:
1. Extract ZIP content to your server. For example to the "/quickapps" directory.
2. Now you must visit "http://example.com/quickapps/" to start the installation screen

You MUST double check that **mod_rewrite** is enabled before start the installation screen.

I hope this helps,
Best regards!

**Comment by ghost** [comment]
Hello,

Now I've done it so like you said. The result is that to me a white page is displayed in the frontend. How can I turn on debugging? Maybe so any errors are displayed and you then what it knows now is. Gotta try the debugging. Thank you in advance!

**Comment by quickapps** [comment]
You can enable debug mode by editing this file before start the installation: https://github.com/quickapps/cms/blob/2.0/plugins/CMS/config/app.php#L23

At your FTP such file should be located at:  /vendor/quickapps/cms/plugins/CMS/config/app.php

You can also try looking at Apache's or PHP's error log files.

**Comment by ghost** [comment]
Very cool! Thank you for telling me that. It really was only to a lack of write access to a directory in the /tmp :)

But thanks to the debug one sees everything and does not have to look far. I am pleased that I can now start the installation.

**Comment by quickapps** [comment]
:)

**Comment by ghost** [comment]
Unfortunately I still have some. I want to have Quick Apps in German and wanted to activate the German language in the backend, but appears to me again this error.

```
changeFlag function (select box, baseURL) {
var icon = $ (selectbox) .val ();
if (icon) { 
$ ('span.flag') HTML ('<img src = "' + baseURL + icon + '" />').
}
}
```

How can that not be going there.

**Comment by ghost** [comment]
Sorry, there was still debugging enabled. Now I test everything first and sign up if I have problems. Thank you!

**Comment by quickapps** [comment]
Ok :+1:,
feel free to contact if you find any problem.
