### ISSUE TITLE
Problem with Login

### ISSUE THREAD

**Issue by ghost** [quickapps/cms#108]
Hello Webdevelopers,

I just wanted to sign me in Quick Apps, and I was shown that I have no rights for /webroot. I have the file with /webroot/index.php CHMOD 777 provided. Is it possible that so leave or is it because of something else. That would be good to know. Thank you.

**Comment by ghost** [comment]
After updating the page it worked again. I do not know if it is the browser cache or something else.

**Comment by quickapps** [comment]
I think you have to chmod the entire /webroot directory recursively,  that is subfolders and files. not just the index. php file mentioned

**Comment by ghost** [comment]
Thanks, I have it now that all directories in /webroot CHMOD 777. That should work.
