### ISSUE TITLE
Not to see created Menu link in the frontend in the Menu

### ISSUE THREAD

**Issue by ghost** [quickapps/cms#109]
I've got a problem with the visibility of a new menu links.

I have a basic Page created and then linked this Page in the menu. All activated, but the link can not be seen. Perhaps I overlooked something and some understanding for a CMS I have.

Thanks for the help in advance

![quickapps_menulinks](https://cloud.githubusercontent.com/assets/7885632/7883284/a8e8059e-0615-11e5-81f9-f90066f3da55.jpg)

**Comment by quickapps** [comment]
I think it may be a problem with cache engine.
I'll take a look, thanks for reporting

**Comment by ghost** [comment]
OK thank you! Happy because the reporting

**Comment by ghost** [comment]
Super has all worked out and now my Page in the menu visible.

**Comment by quickapps** [comment]
Great! :)
