### ISSUE TITLE
Links to us in WYSIWYG does not work

### ISSUE THREAD

**Issue by ghost** [quickapps/cms#110]
Hello Developers,

I'm testing Quick Apps 2.0 beta and I noticed that you can not link in the WYSIWYG editor. My Firefox shows me lower error.

Error: [CKEDITOR.dialog.openDialog] dialogue "link" failed When loading definition.

What could this be the problem? Would appreciate the help very much. Thank you.

![quickapps_links](https://cloud.githubusercontent.com/assets/7885632/7886590/51619eb4-062b-11e5-83b6-6ac1d4e64893.jpg)

**Comment by quickapps** [comment]
have you tried other browser?, I'm testing it under Chrome and seems to work just fine.
For what I found it may be a CKEditor bug. I'll take a deeper look

**Comment by ghost** [comment]
Just now tested again. It works. Probably after the have been fixed with the Menu link, now works Links to us again. This is now in the Firefox browser. Thank you!
