### ISSUE TITLE
Problem with the comment as an anonymous user

### ISSUE THREAD

**Issue by ghost** [quickapps/cms#112]
I've got a problem with the comment as an anonymous user. I have the Captcha setting Are you a human and have it enabled in the options, but under the article when I have commented in the front end and the comments dispatch appears

Error
An Internal Error Has Occurred.

An Internal Error Has Occurred.

Can you test with you if you are logged out, and with Are you a human again? Thank you in advance!

**Comment by quickapps** [comment]
This commit should fix this problem,
let me know if it is working ok so I can close this ticket.

PS: There's a very simple plugin for adding "Disqus" comments to QA that you may like: https://github.com/quickapps-plugins/disqus

Thanks for reporting.

**Comment by ghost** [comment]
With me not working. Can you please check with you ?! If it works in, then I'm doing something wrong. I normally download the new files from that [source](https://github.com/quickapps/cms), and then uploaded to the server. I do not know why it does not want to go with me.

**Comment by quickapps** [comment]
You are right, replacing old files with new ones should do the trick when updating.
I'm testing on my local installation and seems to work just fine. Could you please check the file `/logs/errors.log` and see if there is something strange in it?

**Comment by ghost** [comment]
Yes, a pity, why it does not go with me. And I have just looked at the error.log and there is the following content in it.

I do not understand, unfortunately, but maybe you can tell me something now.    

```
2015-05-30 11:40:58 Error: [BadMethodCallException] Unknown method         "validationUpdate"
Request URL: /quickapps/de_DE/article/artikel-mit-quickapps-2-0-bloggen.html
Stack Trace:
#0 /www/htdocs/w0103f82/quickapps/tmp/aop/quickapps/vendor/quickapps /cms/plugins/Comment/src/Controller/Component/CommentComponent.php(475):  Cake\ORM\Table->__call('validationUpdat...', Array)
#1 /www/htdocs/w0103f82/quickapps/tmp/aop/quickapps/vendor/quickapps/cms/plugins/Comment/src/Controller/Component/CommentComponent.php(475): Comment\Model\Table\CommentsTable->validationUpdate(Object(Cake\Validation\Validator))
#2 /www/htdocs/w0103f82/quickapps/tmp/aop/quickapps/vendor/quickapps/cms/plugins/Comment/src/Controller/Component/CommentComponent.php(228): Comment\Controller\Component\CommentComponent->_createValidator()
#3 /www/htdocs/w0103f82/quickapps/tmp/aop/quickapps/vendor/quickapps/cms/plugins/Content/src/Controller/ServeController.php(139): Comment\Controller\Component\CommentComponent->post(Object(Content\Model\Entity\Content))
#4 [internal function]: Content\Controller\ServeController->details('article', 'artikel-mit-qui...')
#5 /www/htdocs/w0103f82/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Controller/Controller.php(412): call_user_func_array(Array, Array)
#6 /www/htdocs/w0103f82/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#7 /www/htdocs/w0103f82/quickapps/tmp/aop/quickapps/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(Content\Controller\ServeController))
#8 /www/htdocs/w0103f82/quickapps/webroot/index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#9 {main}
```

**Comment by quickapps** [comment]
Seems to be an AOP cache problem, try this:

After replace your installation [files](https://github.com/quickapps/cms/commit/ccccb94e2380930611f8bae4ac4e4bc37603d769), delete this folder: `/tmp/aop/`

**Comment by ghost** [comment]
Many Thanks! It worked, and now you can comment as a guest.
