### ISSUE TITLE
How to install Quicapps on WHM / cPanel

### ISSUE THREAD

**Issue by truongtanhung** [quickapps/cms#114]
Hi guys,
I'm getting problems with install your Quickapps on WHM. It could not Run and notified me alert "500 Internal Server". I'm so Tired for this issue.
Please can you provide me a detail instruction for installing your Quickapps? Thanks so much!

**Comment by truongtanhung** [comment]
Hello men, more info http://76.12.219.242/~epicdirectory/
I'm running on this url. And i can't install your Quickapps on this

**Comment by quickapps** [comment]
We need more information,
check the `/logs/` directory and see if there is an `error.log` file.

You can also try to enable debug mode, edit the following file: `/vendor/quickapps/cms/plugins/CMS/config/app.php`
and change `'debug' => false,` **to** `'debug' => true,`

Does your server meets all the [requirements](https://github.com/quickapps/cms#requirements)?

Check the installation guide as well: http://api.quickappscms.org/book/getting-started/installation.html

**Comment by truongtanhung** [comment]
There are different if i install your Quickapps 1.x on my WHM? And you can provide a instruction for install on WHM? thanks so much
I'm getting empty from /log/.

**Comment by truongtanhung** [comment]
I need to get this install done Today, so i really need your help http://76.12.219.242/~epicdirectory/

**Comment by quickapps** [comment]
Yes, 1.1 and 2.x are different.
Requirements and install instructions for **1.1** can be found here:
https://github.com/quickapps/cms/tree/1.1#requirements

After upload make sure to chmod everything to writable (755, 777, etc).

We can't do anything with the URL you provided, we need logs information, look your cPanel for PHP logs and paste its content here.

Error 500 can be anything, server incompatibilities most of cases, that is why we need to see your server logs...

Regards!

**EDIT:** To enable debug mode in v1.1 you must edit the file `/Config/core.php` as follow:

``` php
Configure::write('debug', 2);
```

And log files in v1.1 are located here: **/tmp/logs/**

**Comment by truongtanhung** [comment]
Thanks Quickapps Team for quickly response.
But I'm getting issue with loading auto Plugins in your CMS. And here is issue with load "CakePlugin::load('FieldDate');"
Please can you show me some solutions with this problem? Thanks so much
Attached file is detail error, i wanna you to see
![error](https://cloud.githubusercontent.com/assets/12932548/8411548/b6990cd6-1eae-11e5-8efe-c6fdc367b4ab.jpg)

**Comment by quickapps** [comment]
When does this happen, before or after the installation ?

This error is commonly related to cache problems.
You can try to **recursively** chmod the "/tmp/" directory to writable, after that you should manually remove all the **files** at `/tmp/` or any subdirectoy.

**Comment by truongtanhung** [comment]
This is after the installation. I clear all files in "/tmp/" and its subfolder. But i'm still getting this issue. Please help me, thanks!

**Comment by quickapps** [comment]
Sounds like a corrupt installation. Did you tried the "manual installation" process?
as described here: https://github.com/quickapps/cms/tree/1.1#manual-installation

Did you tried to install some module or theme that could break your site?

can you attach the following file please? `tmp/cache/cake_plugin_paths`
