### ISSUE TITLE
Helper class Menu\\View\\Helper\\MenuHelperHelper could not be found

### ISSUE THREAD

**Issue by mpeconsulting** [quickapps/cms#115]
Hi,

When I installed using composer create-project -s dev quickapps/website quickapps

I get the following error:

[Tue Jul 21 14:47:49.365210 2015] [:error] [pid 16847] [client xx.xx.xx.xx:xxxxx] PHP Fatal error:  [Cake\View\Exception\MissingHelperException] Helper class Menu\View\Helper\MenuHelperHelper could not be found.\n#0 /var/www/vhosts/mydomain.com/httpdocs/quickapps/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(90): Cake\View\HelperRegistry->_throwMissingClassError('Menu\View\Helpe...', NULL)\n#1 /var/www/vhosts/mydomain.com/httpdocs/quickapps/vendor/cakephp/cakephp/src/View/View.php(960): Cake\Core\ObjectRegistry->load('Menu', Array)\n#2 /var/www/vhosts/mydomain.com/httpdocs/quickapps/vendor/cakephp/cakephp/src/View/View.php(863): Cake\View\View->loadHelper('Menu', Array)\n#3 /var/www/vhosts/mydomain.com/httpdocs/quickapps/vendor/cakephp/cakephp/src/View/View.php(323): Cake\View\View->loadHelpers()\n#4 /var/www/vhosts/mydomain.com/httpdocs/quickapps/vendor/quickapps/cms/plugins/CMS/src/View/View.php(82): Cake\View\View->__construct(Object(Cake\Network\Request), Object(Cake\Network\Response), Object(Cake\Event\EventManager), Array)\n#5 /var/www/vhosts/mydomain.com/httpd in /var/www/vhosts/mydomain.com/httpdocs/quickapps/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 157

Cheers,

Michael

**Comment by quickapps** [comment]
When this occurs?,  before or after the installation proccess?

Were you able to see at least the installation screen as below?

![install screen](http://api.quickappscms.org/book/_images/install-screen.png)

**Comment by mpeconsulting** [comment]
I just get a white screen. No installation screen comes up ... the error is in the apache log.

**Comment by quickapps** [comment]
I was totally unable to reproduce the issue. Fresh installation using composer and seems to work just fine.

Does your server meets all requirements as described here?: http://api.quickappscms.org/book/getting-started/requirements.html

Double check writing permissions on `/tmp` directory (recursively), however I recommend you to `chmod` the entity project's directory.

---

Have you tried any of the packaged pre-release versions? You can find them here:
https://github.com/quickapps/cms/releases ([latest here](https://github.com/quickapps/cms/releases/download/2.0.0-beta2/cms-2-0-0-beta2.zip))
Just download unpack and run

**Comment by mpeconsulting** [comment]
I did not recursively change the permissions on the /tmp folder! (face palm)

**Comment by quickapps** [comment]
I see :sweat_smile:,
so does it work now?

**Comment by mpeconsulting** [comment]
Yes thanks.  Sorry for the slow reply.

Thank you :)
