### ISSUE TITLE
there no way to add or manage content into categories

### ISSUE THREAD

**Issue by surjit** [quickapps/cms#116]
Hi

I have need new taxonomy here /admin/taxonomy/vocabularies
also added few terms, but there no interface allows me to add new content understand taxonomy
even that does not show in the category list here admin/content/manage/add/article

**Comment by quickapps** [comment]
Hi,
Taxonomy plugin provides a "Term Reference" field which can be attached to content types, that allows you create contents and assign them to certain "categories" (terms of certain vocabulary).

To add a new "Term Reference" field go to `Content -> Content Types`, click in the icon `Manage Fields` of the Content Type you want to manage, there you will be able to attach a new `Term Reference`, you will need to provide a vocabulary from which the field should read the terms that will be presented to users in the edit form.
