### ISSUE TITLE
 Helper class CommentHelper could not be found.

### ISSUE THREAD

**Issue by surjit** [quickapps/cms#117]
2015-08-10 02:30:34 Error: [Cake\View\Exception\MissingHelperException] Helper class CommentHelper could not be found.
Request URL: /en_US/article/hello-world.html
Stack Trace:
#0 vendor\cakephp\cakephp\src\Core\ObjectRegistry.php(91): Cake\View\HelperRegistry->_throwMissingClassError('Comment', 'Content')
#1 vendor\cakephp\cakephp\src\View\HelperRegistry.php(70): Cake\Core\ObjectRegistry->load('Content.Comment')
#2 vendor\cakephp\cakephp\src\View\View.php(840): Cake\View\HelperRegistry->__isset('Comment')
#3 vendor\quickapps\cms\plugins\Content\src\Template\Element\render_content.ctp(38): Cake\View\View->__get('Comment')
#4 vendor\quickapps\cms\plugins\CMS\src\View\View.php(282): include('F:\hobby\quicka...')
#5 vendor\cakephp\cakephp\src\View\View.php(883): CMS\View\View->_evaluate('F:\hobby\quicka...', Array)
#6 vendor\cakephp\cakephp\src\View\View.php(1250): Cake\View\View->_render('F:\hobby\quicka...', Array)
#7 vendor\cakephp\cakephp\src\View\View.php(471): Cake\View\View->_renderElement('F:\hobby\quicka...', Array, Array)
#8 F:\hobby\quickapp2\vendor\quickapps\cms\plugins\Content\src\Event\ContentHook.php(122): Cake\View\View->element('Content.render_...', Array)
#9 F:\hobby\quickapp2\vendor\cakephp\cakephp\src\Event\EventManager.php(387): Content\Event\ContentHook->renderContent(Object(Cake\Event\Event), Object(Content\Model\Entity\Content))
#10 F:\hobby\quickapp2\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#11 vendor\quickapps\cms\plugins\CMS\src\View\View.php(178): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#12 vendor\quickapps\cms\plugins\Content\src\Template\Serve\details.ctp(13): CMS\View\View->render(Object(Content\Model\Entity\Content))
#13 vendor\quickapps\cms\plugins\CMS\src\View\View.php(282): include('F:\hobby\quicka...')
#14 vendor\cakephp\cakephp\src\View\View.php(883): CMS\View\View->_evaluate('F:\hobby\quicka...', Array)
#15 vendor\cakephp\cakephp\src\View\View.php(560): Cake\View\View->_render('F:\hobby\quicka...')
#16 vendor\quickapps\cms\plugins\CMS\src\View\View.php(189): Cake\View\View->render(NULL, NULL)
#17 vendor\cakephp\cakephp\src\Controller\Controller.php(589): CMS\View\View->render(NULL, NULL)
#18 vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#19 vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(Content\Controller\ServeController))
#20 F:\hobby\quickapp2\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#21 {main}

**Comment by quickapps** [comment]
I think it may be related to https://github.com/quickapps/cms/issues/115 , could you please check it?
