### ISSUE TITLE
bin/qs on linux has to be "cleaned"

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#118]
Hello,

Just to say that to manage to execute the bin/qs command I'd need to run dos2unix on that file, otherwise an error occurred. Maybe you can just add a note on the documentation.

Thanks

**Comment by quickapps** [comment]
Hi,
What do you mean with "clean"?

QACMS provides two "qs" files, one for Windows and another for Linux (`bin/qs.bat` and `bin/qs` respectively).

QACMS's `bin/qs` file is exactly the same provided by CakePHP's, just renamed from `bin/cake` to `bin/qs`.

**Comment by Gabri** [comment]
Yes, I mean the executable file `bin/qs` for Linux systems. I had the same behavior described in this question:
http://stackoverflow.com/questions/19813818/cakephp-cake-command-returns-no-such-file-or-directory
That file has line endings in the Windows format, that was the problem.

A question: if qs is just a cake rename ...why is not possible to "bake" from that shell?

**Comment by quickapps** [comment]
Oh I see,
- I modified that file time ago using Windows editor :weary: ... I'll take a look this afternoon.
- CakePHP's Bake is now an external plugin, which is not included by default in QACMS.

Can you please open a new ticket to remember to include this plugin by default in next releases?
I think we can do the same for DebugKit.
