### ISSUE TITLE
Error while importing data for table "eav_values". Details: Cannot convert value to bool

### ISSUE THREAD

**Issue by web-ap** [quickapps/cms#130]
Hi,
I'm trying to install Quickapps and I have this issue during DB installation : 
**Error while importing data for table "eav_values". Details: Cannot convert value to bool
Error importing "C:\wamp\www\quickapps\vendor\quickapps-plugins\installer\config\fixture\EavValuesFixture.php".**

I downloaded it with Composer.

What should I do? 
Thanks.

**Comment by quickapps** [comment]
We will take a look,

seems to be related with CakePHP's core changes, as you can see here:
https://groups.google.com/forum/#!topic/cake-php/IFDBaMR1I30

**Comment by web-ap** [comment]
Thanks for your quick reply. If you find something, please let me know.

**Comment by emaildostrider** [comment]
Is there any way to install cms with cakephp 3.1.1 using the composer? I'm having this same problem and can not install. Thank you.

**Comment by botchris** [comment]
@emaildostrider You can modify your "composer.json" ([ROOT/composer.json](https://github.com/quickapps/website/blob/master/composer.json#L11)) and change this line:

``` json
    "cakephp/cakephp": "~3.0",
```

For this:

``` json
    "cakephp/cakephp": "3.1.1",
```

**Comment by quickapps** [comment]
The problem has been already fixed by CakePHP core team here: https://github.com/cakephp/cakephp/issues/7583

So we've decided to stay on CakePHP 3.1.1 until next bugfix release (3.1.3): https://github.com/quickapps/website/commit/e2907ccd1ee55ae3cf7ffe86a1a642a6be7ca5ac

Closing and marking as solved
