### ISSUE TITLE
Remove CMS dependency from EAV

### ISSUE THREAD

**Issue by Marlinc** [quickapps/cms#131]
Is it really necessary to have a dependency on the QuickApps CMS in the EAV plugin? As far as I know its not being used by EAV.

We'd like to use the EAV plugin but this is holding us back.

**Comment by quickapps** [comment]
Hi,

I believe EAV relies on some of the global functions defined by CMS plugin.

We been using EAV plugin in some private projects without any problem.
Are you experiencing some problems when installing/using the EAV plugin?

**Comment by Marlinc** [comment]
Hello there,

First of all thank you for responding so quickly.

Its not that we're running into problems now but more that a dependency is being added that's not being used. We don't need the CMS itself, just the EAV plugin. There shouldn't be the need to add the CMS as dependency since the plugin doesn't have a real requirement for it.

**Comment by quickapps** [comment]
Hi,

I understand, but we first need to make sure there are zero dependencies before deciding to removing it. A quick look at source code we found this:

https://github.com/quickapps-plugins/eav/blob/master/src/Model/Table/EavAttributesTable.php#L36

Which is optional, so maybe  we can mark CMS plugin as suggested at EAV's composer.json

Marking as RFC, we will study this.
Thanks!

**Comment by Marlinc** [comment]
Including it as a suggestion in the composer file would make sense. Thanks for considering it!
