### ISSUE TITLE
possible variable typo in `bootstrap_site.php`

### ISSUE THREAD

**Issue by cwbit** [quickapps/cms#133]
Hi! Was just poking thru source and noticed an `if(..)` checking for `$clasLoader` instead of `$classLoader` (_clas_ instead of _clas**s**_) - I wasn't sure if this was a snafu so I wanted to create an issue just in case - the issue can be seen [here](https://github.com/quickapps/cms/blob/2.0/plugins/CMS/config/bootstrap_site.php#L29)

**Comment by botchris** [comment]
You are right, it should be `$classLoader`.
This line allow to use a custom class loader, which is almost never... so it is not critical at all unless you are planning to a custom loader instead of default omposer's.

Thanks for reporting it, we'll solve this ASAP.

**Comment by cwbit** [comment]
cool - no sweat

thanks for making the project open source!
