### ISSUE TITLE
Route matching error when slug generator is special characters.

### ISSUE THREAD

**Issue by LeLuyen** [quickapps/cms#134]
Have a bug with the slug generator when working with special characters.

Please fix it

**Comment by botchris** [comment]
Can you please provide an example of failing slug? and the error you are getting?

**Comment by LeLuyen** [comment]
Hi ChristopherCastro,
When I type for content of title of an article as utf-8 character as 'Ối giời ơi', the system gives slug generator's url is ../es_Es/article/Ối-giời-oi.html

When I access to the ../es_Es/article/Ối-giời-oi.html address, The system informed "A route matching "/es_ES/article/%E1%BB%90i-gi%E1%BB%9Di-oi.html" could not be found"

**Comment by botchris** [comment]
Which version of QACMS are you using?,
I did a new fresh installation **using composer**, and everything seems to work just fine:

![captura](https://cloud.githubusercontent.com/assets/749463/11609658/cb54c79a-9b8c-11e5-8447-c6a825483e79.PNG)

**Comment by LeLuyen** [comment]
Hi Chris,

I'm using QACMS version 2.0.0-beta2 with ubuntu OS 14.04, PHP 5.6 and mysql 5.6

What are the version of QACMS use by you?

Thanks you!

**Comment by botchris** [comment]
Ok, I think the version you are using is the problem.
When you say "2.0.0-beta2" you [mean this one](https://github.com/quickapps/cms/releases/tag/2.0.0-beta2)?

I'm using the latest available (untagged), that is "dev-master"? Installed using composer:

> composer create-project -s dev quickapps/website [website_name]

(Note the `-s dev` part)

**Comment by LeLuyen** [comment]
Hi Chris,
Thank you for your information.

> When you say "2.0.0-beta2" you mean this one?
> Yes.
> I got the latest source with composer command and test, it's not problem.
> Please close it.
> Thanks you!

**Comment by LeLuyen** [comment]
Hi Chris,

If use composer create-project -s dev quickapps/website [website_name] => not problem.
If download from https://github.com/quickapps/cms/releases/tag/2.0.0-beta2 url.
cd /var/www/html
unzip 2.0.0-beta2.zip
cd cms-2-0-0-beta2/vendor/quickapps/cms
composer update
Result for update is Server error(500) => have problem.
How to get latest source with stable?
Need to cd each plugin, after update, right?

**Comment by LeLuyen** [comment]
Hi Chris,

With latest source.

When i access to http://127.0.0.1/quickapps/en_US/admin/menu/links/menu/2 or http://127.0.0.1/quickapps/en_US/admin/taxonomy/terms/vocabulary/1

Have error:

"
Error	
An Internal Error Has Occurred.
You cannot issue a count on a Collection.
"

**Comment by botchris** [comment]
**You should always use Composer to get latest source and/or update.**
For instance, for create a clean installation using latest source code use:

``` bash
composer create-project -s dev quickapps/website [website_name]
```

(Where `[website_name]` is the name of the directory you want composer to place the code)

---

To update current installation:

``` bash
composer update
```
