### ISSUE TITLE
The bugs on latest sources

### ISSUE THREAD

**Issue by LeLuyen** [quickapps/cms#135]
Hi Chris,
I'm general the all bugs at this issues, please interesting those and fix bug.
Environment: Ubuntu 14.04, PHP 5.6, MySql 5.6
- [x] **1. Bug about Wysiwyg, you can see attached.**
  ![image](https://cloud.githubusercontent.com/assets/2620445/11706850/5584f9ee-9f2f-11e5-8281-df4821fc437a.png)
- [x] **2. Bug about Menu Link, you can see attached.**
  ![image](https://cloud.githubusercontent.com/assets/2620445/11706860/8379a494-9f2f-11e5-8e69-bb394fda36b6.png)
- [x] **3. Bug about taxonomy, you can see attached.**
  ![image](https://cloud.githubusercontent.com/assets/2620445/11706873/a768bba6-9f2f-11e5-87de-8ba8e6c77b7f.png)
- [x] **4. Bug about manager fields, you can see attached.**
  ![image](https://cloud.githubusercontent.com/assets/2620445/11706909/02c5f342-9f30-11e5-80fa-11759ef5d820.png)
- [x] **5. Bug about comment, you can see attached.**
  ![image](https://cloud.githubusercontent.com/assets/2620445/11706923/23a37198-9f30-11e5-8dc6-1e07da16d874.png)
- [x] **6. Bug about loading plugin, you can see attached.**
  ![image](https://cloud.githubusercontent.com/assets/2620445/11706940/520b25f8-9f30-11e5-9cd6-a2f282f7466e.png)
- [x] **7. Bug about manager user(add new user), you can see attached.**
  ![image](https://cloud.githubusercontent.com/assets/2620445/11706960/7d458808-9f30-11e5-9b19-534369d17d50.png)
- [x] **8. Bug about system configuration, you can see attached.**
  ![image](https://cloud.githubusercontent.com/assets/2620445/11706969/a2be6abe-9f30-11e5-9d59-692236cba48d.png)
- [x] **9. Bug about search with categories and term, you can see attached.**
  ![image](https://cloud.githubusercontent.com/assets/2620445/11706991/eae855e8-9f30-11e5-9aa7-f251cc94e1f8.png)
- [x] **10. Bug about search with categories and term as language, you can see attached.**
  ![image](https://cloud.githubusercontent.com/assets/2620445/11707000/2bd416c8-9f31-11e5-84b1-a488c1471f6a.png)
  ![image](https://cloud.githubusercontent.com/assets/2620445/11707006/4151a15a-9f31-11e5-9283-09650d2f7239.png)

Thanks you!

**Comment by botchris** [comment]
Can you please provide more information about 2, 3 & 8?
I would need to see your `/logs/errors.log` file to get an idea of what is causing that error screen

**Comment by botchris** [comment]
Also, what is "latest source"?
which version are you using? you should use `dev-master` from composer installation and avoid [this one](https://github.com/quickapps/cms/releases/tag/2.0.0-beta2)

**Comment by LeLuyen** [comment]
Hi Chris

Thanks you for your comment.

Yes, I'm using the dev-master
The latest sources are the sources was pushed by you at 2015/12/06.

Today, you are pushing new sources, I'm getting source and check it.

If have problem, I will report problem to you

Thanks you very much!

**Comment by botchris** [comment]
Bugs 1 & 7 can be related to AOP API, seems like your installation is failing to inject plugin's Aspect classes.

Can you please check that your `tmp` directory is writable?
AOP API needs to create some files at `/tmp/aop`,

Another thing you can try: Manually delete this directory (`/tmp/aop`)

**Comment by LeLuyen** [comment]
Hi Chris,

Great.

The /tmp directory is writable, you can see
![image](https://cloud.githubusercontent.com/assets/2620445/11733893/dc5ffa3a-9fe4-11e5-96ef-5dbf0d32f05b.png)

On bug 7, I think the values of field 'settings' on plugins table with the name is 'User' can missing keys.
Bugs 2,3,8 seems ok.
Bugs 9,10, how to search with content type is "page' (find/type:page), could you change?
![image](https://cloud.githubusercontent.com/assets/2620445/11734297/88782fe2-9fe8-11e5-94e1-c597bbb444ed.png)

Thanks you!

**Comment by botchris** [comment]
Ok, I'll keep looking what is causing 1 & 7.

What do you mean `type:page`? The type search operator works just fine, the attached image I can see there is `type:blog` instead of `type:page`
![captura](https://cloud.githubusercontent.com/assets/749463/11741213/bd893708-9ff7-11e5-96a7-6d5a51ce7379.PNG)

**Comment by LeLuyen** [comment]
Hi Chris,

It means, I want to search with slug of content_type table like 'page'. Now, it works.

I'm finding for causing 1, but don't find.

Thanks you!

**Comment by LeLuyen** [comment]
Hi Chris,

About bugs 2,3,8. Those are repeating.

You can test with ../admin/content/fields/view-mode-list/search-result?type=article url

Here are logs:
2015-12-11 16:52:11 Error: [Cake\View\Exception\MissingTemplateException] Template file "FieldUI\view_mode_list.ctp" is missing.
Request URL: /20151211/en_US/admin/content/fields/view-mode-list/search-result?type=article
Stack Trace:
#0 D:\ApachePhp\htdocs\20151211\tmp\aop\20151211\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 D:\ApachePhp\htdocs\20151211\tmp\aop\20151211\vendor\quickapps\cms\plugins\CMS\src\View\View.php(189): Cake\View\View->render(NULL, NULL)
#2 D:\ApachePhp\htdocs\20151211\tmp\aop\20151211\vendor\cakephp\cakephp\src\Controller\Controller.php(611): CMS\View\View->render(NULL, NULL)
#3 D:\ApachePhp\htdocs\20151211\tmp\aop\20151211\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#4 D:\ApachePhp\htdocs\20151211\tmp\aop\20151211\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(Content\Controller\Admin\FieldsController))
#5 D:\ApachePhp\htdocs\20151211\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}

**Comment by LeLuyen** [comment]
Hi Chris,

I want to find as find/vocabulary:articles-categories and give the term as grid type.

How to find an articles categories?

Thanks you!

**Comment by LeLuyen** [comment]
Hi Chris,
Have a bug about show categories as language.
Please fix it.
Thanks you!

**Comment by LeLuyen** [comment]
Hi Chris,

Have a bug about DateField.

![image](https://cloud.githubusercontent.com/assets/2620445/11806331/e2641e44-a344-11e5-828b-bf0581e60532.png)

**Comment by LeLuyen** [comment]
Hi Chris,

About Wysiwyg bug, I found your config have problem

You can see the line 30 of /vendor/composer/autoload_psr4.php file

`'CMS\\' => array($vendorDir . '/quickapps/cms/plugins/CMS/src', $vendorDir . '/quickapps-plugins/cms/src'),`

Firstly the system load '/quickapps/cms/plugins/CMS/src', if it is not find, the system will load quickapps-plugins/cms/src.

I think you need remove $vendorDir . '/quickapps/cms/plugins/CMS/src' from array of CMS or remove /vendor/quickapps folder

Thanks you!

**Comment by LeLuyen** [comment]
Hi Chris,

About manager user bug.

I think you need make default value for Minimum password length(password_min_length) when setup site with User plugin.

Thanks you!

**Comment by botchris** [comment]
Hi there,

The `/vendor/composer/autoload_psr4.php` file is automatically generated by Composer during the installatin proccess. It's not part of QACMS code, except if you are using one of the [tagged versions](https://github.com/quickapps/cms/releases) as they are full installations packaged as ZIP.

I recommend to start a fresh installation and check if the problem persists.
However, fixing this file solves the WYSIWYG problem?

---

Can you please open a new ticket about the "Minimum password length" thing

Best regards

**Comment by LeLuyen** [comment]
Hi Chris,

> However, fixing this file solves the WYSIWYG problem?

Yes,
Other way, you can remove 'quickapps' folder.

Thanks you!

**Comment by botchris** [comment]
Hi,

This folder comes from the [required-dev](https://github.com/quickapps/website/blob/1ea5ba081df3bb3624503530d3cde40f0f848bec/composer.json#L16) clause in the main composer.json. I think it may be causing some conflicts with the `cms` plugin as both use `CMS` as psr4 namespace.

This [commit should fix the problem](https://github.com/quickapps/website/commit/d0933a7ecb011fae3e11a787be4e9bc87500b567), and other similar issues as #148
