### ISSUE TITLE
Editor not displaying in Add Content / Add Block Quick App CMS 3 version

### ISSUE THREAD

**Issue by mananmodi22** [quickapps/cms#137]
Editor not displaying in Add Content / Add Block Quick App CMS  v2.0.0-beta2 version, please let us know configuration soon for same.

**Comment by botchris** [comment]
Please avoid using[ beta2 package](https://github.com/quickapps/cms/releases/tag/2.0.0-beta2) (as it has some problems with AOP cache that may be causing this issue and similars). Use manual installation instead using composer as described [here](https://github.com/quickapps/cms#installing-quickappscms).

PS: Also make sure your `/tmp` directory has full write permissions.

Let us know if you have solved this problem,
best regards!

---

Manual installation (from dev branch) seems to work just fine:
![8cfb932ec9cb310c20f6c0c8bd4c6a1f](https://cloud.githubusercontent.com/assets/749463/13406234/ad64a5aa-df22-11e5-9e5b-01e85b5d8ac3.png)
