### ISSUE TITLE
Quickapps 2 Documentation

### ISSUE THREAD

**Issue by wormtreat** [quickapps/cms#140]
Is this a dead project? Your documentation pages are broken, so it's practically impossible for anyone to use it... Any chance of getting some documentation on your latest product? 

http://api.quickappscms.org/2.0/
http://api.quickappscms.org/book/

**Comment by botchris** [comment]
We've just migrated project's domain and host to a new VPS few days ago, our old hosting had an old version of PHP so QACMS v2.x demo couldn't be installed on that server... So no, not dead at all ;)

BTW, `http://api.quickappscms.org/book/` will be moved to a new subdomain `book.quickappscms.org`

**Comment by wormtreat** [comment]
Wow, thank you for the reply! I'm pressed on a project and hit a wall right
off the bat with the missing docs. Glad to hear it's not dead, I used v1 a
while back and was pretty pleased.

Thank you,
Evan

**Comment by botchris** [comment]
Closing. As mentioned, website migrated to new server.

---

**API subdomain**: http://api.quickappscms.org/
**BOOK subdomain**: http://book.quickappscms.org/

...and our brand new demo website which automatically reboots every hour:

**DEMO subdomain**: http://demo.quickappscms.org/
