### ISSUE TITLE
Bug with stripLanguagePrefix method

### ISSUE THREAD

**Issue by LeLuyen** [quickapps/cms#145]
Hi Chris

Have bug on stripLanguagePrefix() method

Example:

Have 3 languages was set as ja,fr,en_US

I run on domain http://quickapp.com.ja/en_US/article/test.html

Now when using stripLanguagePrefix -> result of that url is http://quickapp.com/./article/test.html

Please fix

**Comment by botchris** [comment]
Fixed here c7e3603d06bc670ab735a254fc2bdef429b510b6

---

thanks for reporting!
