### ISSUE TITLE
Have bug in _requestMatches() method of LinkHelper class

### ISSUE THREAD

**Issue by LeLuyen** [quickapps/cms#146]
Hi Chris,

What's happen when the url format with special charactor as http://quickapp.cms/article/ພ-ທ-ເປ-ດໜ-ວຍບ-ລ-ການ-ດອນໜ-ນ-ວ-ນທ-04-05-2015.html? It is not matching true, right?
`$path = '/' . $request->url;`

Below line 228 I think we need to decode url with special charactor.
My way:

```
//decode url with special charactor
if (preg_match("@^[a-zA-Z0-9%+-_]*$@", $path)){
    $path = urldecode($path);
}
```

Please fix with your way,

Thanks you!

**Comment by LeLuyen** [comment]
Hi Chris,
I'm reading source.

What's happen when the case is 'any' or 'none'?

Thanks you!

**Comment by LeLuyen** [comment]
Hi Chris,

When the case is 'any' or 'none' => result of isActive method is _requestMatches() method.

Please see comment no 1 reporting by me.

Please fix, thanks you!

**Comment by LeLuyen** [comment]
Hi Chris,

It's happening with _urlMatch method of Region class.

For more info you can see the attachment

![image](https://cloud.githubusercontent.com/assets/2620445/14132347/20932a66-f66f-11e5-982b-797d5a43fbdc.png)

![image](https://cloud.githubusercontent.com/assets/2620445/14132367/50f695e4-f66f-11e5-93af-9e4df526c7e2.png)

**Comment by botchris** [comment]
Oh, I see the problem.

I'll take a deeper look

**Comment by LeLuyen** [comment]
Hi Chris,

Could you fix on _urlMatch method of Region class with Block plugin?

Thanks you!
