### ISSUE TITLE
Minimum password length

### ISSUE THREAD

**Issue by LeLuyen** [quickapps/cms#148]
Hi Chris,

Please fix when create new user after finish installing
![image](https://cloud.githubusercontent.com/assets/2620445/11706960/7d458808-9f30-11e5-9b19-534369d17d50.png)

Thanks you!

**Comment by botchris** [comment]
Closing, d0933a7ecb011fae3e11a787be4e9bc87500b567 should fix the problem, and other similar issues as #148 or #135
