### ISSUE TITLE
About Security of folder

### ISSUE THREAD

**Issue by LeLuyen** [quickapps/cms#149]
Hi Chris,

I found about security of folder
When I access with any urls as
www.example.com/css/,www.example.com/files,www.example.com/img,www.example.com/js... the site will show all folders and files

You can see the attach file.

![image](https://cloud.githubusercontent.com/assets/2620445/15034309/66d26b68-129e-11e6-8f72-049c5988e4f2.png)

Please fix.

With my fix. I create .htaccess file with content
`<FilesMatch ".(php|php3|phtml|inc|c|pl|cgi)$">
Order Allow,Deny
Deny from all
</FilesMatch>`

**Comment by botchris** [comment]
Hi there,

this occurs due to an "incorrect" configuration of your apache server. Directory browsing can (and should) be disabled at apache's configuration file: /etc/apache2/apache2.conf

You should remove any mention to `Options Indexes`

---

PS: Closing as it's not really an issue or bug
