### ISSUE TITLE
It redirect on install screen again

### ISSUE THREAD

**Issue by dimple-varshaaweblab** [quickapps/cms#151]
I have installed plugin in cakephp 3.2 on frineday. and when i open cms on monday it redirect me on install screen http://awesomescreenshot.com/0745xa8t8d . also when i am filling databse information it shows me an error http://awesomescreenshot.com/0d95xa8z98.

Kindly reply me as soon as possible.

**Comment by botchris** [comment]
The only way to reach a fresh installation state is by removing the `ROOT/config/settings.php` file. As you can see here: https://github.com/quickapps/cms/blob/2.0/plugins/CMS/config/routes_site.php#L17

Make sure the `settings.php` file exists, and if you are running Linux make sure that the file is readable by the user running PHP process. (use `chown` and `chmod` commands)
