### ISSUE TITLE
css issue

### ISSUE THREAD

**Issue by dimple-varshaaweblab** [quickapps/cms#153]
Hello,

I have installed plugin.i am facing issue of css(http://awesomescreenshot.com/0ce5xc5y2e)
Your help would be greatly appreciated.

Thank you
Dimple

**Comment by akkaweb** [comment]
@dimple-varshaaweblab from your screenshot, it appears your CSS is fine, or at least, most of the CSS files loaded fine. Did you try refreshing the page?

**Comment by dimple-varshaaweblab** [comment]
http://awesomescreenshot.com/0425xeapa6  Please look at demo.there is good style. and on my server http://awesomescreenshot.com/0ce5xc5y2e. are you able to differentiate?

**Comment by botchris** [comment]
Looks like that Aspect classes are not working properly and are failing to inject Bootstrap css styles. It may be related to #154, and as explained at https://github.com/quickapps/cms/issues/154#issuecomment-225255319:
Upgrade your isntallation and see if AOP 2.0 solves this problem.

**Also**, [make sure that your are not using](https://github.com/quickapps/website/commit/d0933a7ecb011fae3e11a787be4e9bc87500b567) the `quickapps/cms` package, it is know to be problematic when working on production environments. You should not have the following package directory `ROOT/vendor/quickapps`

Try `composer remove quickapps/cms` if you need to.
