### ISSUE TITLE
cache directory issue

### ISSUE THREAD

**Issue by dimple-varshaaweblab** [quickapps/cms#154]
When i remove any view files from aop cache then files is not created automatically. it gives me following error in error log.

 05:56:26 Warning: Warning (2): mkdir() [<a href='http://php.net/function.mkdir'>function.mkdir</a>]: File exists in [/media/data/developer/dimple/cake_cms/vendor/goaop/framework/src/Instrument/Transformer/CachingTransformer.php, line 108]
Request URL: /cake_cms/en_US/admin/user/fields/attach
Referer URL: http://dimple.vtest/cake_cms/en_US/admin/user/fields
Client IP: 192.168.21.71
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
mkdir - [internal], line ??
Go\Instrument\Transformer\CachingTransformer::transform() - ROOT/vendor/goaop/framework/src/Instrument/Transformer/CachingTransformer.php, line 108
Go\Instrument\ClassLoading\SourceTransformingLoader::transformCode() - ROOT/vendor/goaop/framework/src/Instrument/ClassLoading/SourceTransformingLoader.php, line 146
Go\Instrument\ClassLoading\SourceTransformingLoader::filter() - ROOT/vendor/goaop/framework/src/Instrument/ClassLoading/SourceTransformingLoader.php, line 102
stream_get_contents - [internal], line ??
Go\Instrument\Transformer\FilterInjectorTransformer::rewrite() - ROOT/vendor/goaop/framework/src/Instrument/Transformer/FilterInjectorTransformer.php, line 106
Go\Instrument\ClassLoading\AopComposerLoader::loadClass() - ROOT/vendor/goaop/framework/src/Instrument/ClassLoading/AopComposerLoader.php, line 97
spl_autoload_call - [internal], line ??
CMS\View\View::shortcodes() - ROOT/tmp/aop/cake_cms/vendor/quickapps-plugins/cms/src/Shortcode/ShortcodeTrait.php, line 86
CMS\View\View::renderLayout() - ROOT/tmp/aop/cake_cms/vendor/quickapps-plugins/cms/src/View/View.php, line 209
Cake\View\View::render() - ROOT/tmp/aop/cake_cms/vendor/cakephp/cakephp/src/View/View.php, line 592
CMS\View\View::render() - ROOT/tmp/aop/cake_cms/vendor/quickapps-plugins/cms/src/View/View.php, line 189
Cake\Controller\Controller::render() - ROOT/tmp/aop/cake_cms/vendor/cakephp/cakephp/src/Controller/Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - ROOT/tmp/aop/cake_cms/vendor/cakephp/cakephp/src/Routing/Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - ROOT/tmp/aop/cake_cms/vendor/cakephp/cakephp/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37

Please help me to fix it.

**Comment by botchris** [comment]
We've moved to AOP 2.0 #155 which solves several know issues related to cache.
Remember to give write permissions to the `ROOT/tmp` directory, also instead of deleting just a slected set of cache files I would recommend to delete the entire directory `ROOT/tmp/aop/*`

Try to update your QACMS installation in order to see if AOP 2.0 solves this issue.
