### ISSUE TITLE
AOP Error

### ISSUE THREAD

**Issue by akkaweb** [quickapps/cms#156]
I am trying to setup an app using the latest changes, but I am getting the following error:

`Error: [TypeError] Argument 2 passed to Cake\View\Helper\FormHelper__AopProxied::create() must be of the type array, null given, called in /var/www-dev/domain.com/vendor/goaop/framework/src/Aop/Framework/DynamicClosureMethodInvocation.php on line 60`

This happens when I try to access `/admin/`, like so `http://domain.com/en_US/admin/login`

I will keep on looking, but any idea why this is happening?

**Comment by akkaweb** [comment]
Entire error stack

`2016-06-15 04:04:25 Error: [TypeError] Argument 2 passed to Cake\View\Helper\FormHelper__AopProxied::create() must be of the type array, null given, called in /var/www-dev/domain.com/vendor/goaop/framework/src/Aop/Framework/DynamicClosureMethodInvocation.php on line 60
Request URL: /en_US/login
Referer URL: http://domain.com/
Client IP: 73.234.59.17
Stack Trace:
#0 /var/www-dev/domain.com/vendor/goaop/framework/src/Aop/Framework/DynamicClosureMethodInvocation.php(60): Cake\View\Helper\FormHelper__AopProxied->create(Object(User\Model\Entity\User), NULL)
#1 /var/www-dev/domain.com/vendor/quickapps-plugins/bootstrap/src/Aspect/FormHelperAspect.php(89): Go\Aop\Framework\DynamicClosureMethodInvocation->proceed()
#2 /var/www-dev/domain.com/vendor/goaop/framework/src/Aop/Framework/AroundInterceptor.php(34): Bootstrap\Aspect\FormHelperAspect->alterCreate(Object(Go\Aop\Framework\DynamicClosureMethodInvocation))
#3 /var/www-dev/domain.com/vendor/goaop/framework/src/Aop/Framework/DynamicClosureMethodInvocation.php(43): Go\Aop\Framework\AroundInterceptor->invoke(Object(Go\Aop\Framework\DynamicClosureMethodInvocation))
#4 /var/www-dev/domain.com/vendor/goaop/framework/src/Aop/Framework/AbstractMethodInvocation.php(89): Go\Aop\Framework\DynamicClosureMethodInvocation->proceed()
#5 /var/www-dev/domain.com/tmp/aop/_proxies/vendor/cakephp/cakephp/src/View/Helper/FormHelper.php(559): Go\Aop\Framework\AbstractMethodInvocation->__invoke(Object(CMS\View\Helper\FormHelper), Array)
#6 /var/www-dev/domain.com/vendor/quickapps-plugins/user/src/Template/Gateway/login.ctp(14): Cake\View\Helper\FormHelper->create(Object(User\Model\Entity\User))
#7 /var/www-dev/domain.com/vendor/quickapps-plugins/cms/src/View/View.php(283): include('/var/www-dev/ak...')
#8 /var/www-dev/domain.com/vendor/cakephp/cakephp/src/View/View.php(952): CMS\View\View->_evaluate('/var/www-dev/ak...', Array)
#9 /var/www-dev/domain.com/vendor/cakephp/cakephp/src/View/View.php(587): Cake\View\View->_render('/var/www-dev/ak...')
#10 /var/www-dev/domain.com/vendor/quickapps-plugins/cms/src/View/View.php(189): Cake\View\View->render(NULL, NULL)
#11 /var/www-dev/domain.com/vendor/cakephp/cakephp/src/Controller/Controller.php(611): CMS\View\View->render(NULL, NULL)
#12 /var/www-dev/domain.com/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(120): Cake\Controller\Controller->render()
#13 /var/www-dev/domain.com/vendor/cakephp/cakephp/src/Routing/Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(User\Controller\GatewayController))
#14 /var/www-dev/domain.com/webroot/index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#15 {main}
`

**Comment by akkaweb** [comment]
I think the issue might be because I setup my system with PHP 7. I will install PHP 5.6 and give it another try.

**Comment by akkaweb** [comment]
Cant get it to work, even though I have installed a new box with php 5.6. The issue is due to the Splat Operator.

`2016-06-15 14:35:05 Error: Fatal Error (4): syntax error, unexpected '.' in [/var/www-dev/akkaweb.com/vendor/goaop/framework/src/Aop/Framework/DynamicClosureMethodInvocation.php, line 60]
Request URL: /installer/startup/language?q=%2Finstaller%2Fstartup%2Flanguage
Client IP: 73.234.59.17
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 215
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??
`

**Comment by botchris** [comment]
I thinks can be caused by this line:
https://github.com/quickapps/cms/blob/2.0/plugins/Bootstrap/src/Aspect/FormHelperAspect.php#L88

Force a cast to an empy array should fix this:

``` php
$this->setProperty($invocation, 'arguments', [$model, (array)$options]);
```
