### ISSUE TITLE
VENDOR_INCLUDE_PATH is incorrect

### ISSUE THREAD

**Issue by paulrwest** [quickapps/cms#162]
Installed version: quickapps/cms (2.0.x-dev 095b093)
Running on Windows 10  XAMPP Version 7.0.6

/vendor/quickapps/cms/plugins/CMS/config/paths.php:45

`tryDefine('VENDOR_INCLUDE_PATH', dirname(dirname(dirname(__DIR__))))) . DS);`

The above only goes up to /cms/ directory not up to /vendor/ it needs to go up 5 levels so should be changed to:

`tryDefine('VENDOR_INCLUDE_PATH', dirname(dirname(dirname(dirname(dirname(__DIR__))))) . DS);`

**Comment by botchris** [comment]
You have an invalid installation. The `quickapps/cms` package (this repo) is a development repository, here is where we perform CI and then split each plugin into separated repos.
- Dev repo: https://github.com/quickapps/cms
- Plugins: https://github.com/quickapps-plugins
- **Deployment repo**: https://github.com/quickapps/website

That is why you should install using composer and the deployment repo:

``` bash
composer create-project -s dev quickapps/website [your_website_name]
```

---

On regular installation there is no `/vendor/quickapps/cms/plugins/CMS/` directory, the `cms` plugin should be located at `/vendor/quickapps-plugins/cms`, and so, from `ROOT/vendor/quickapps-plugins/cms/config` to `ROOT/vendor/` there are only 3 levels.

**Comment by botchris** [comment]
Here is a screenshot of how a correct installation should looks like:

![qa-production-tree](https://cloud.githubusercontent.com/assets/749463/18264669/fe586b5c-7411-11e6-8e9f-4498b2a09c41.png)

**Comment by paulrwest** [comment]
Thanks Chris, Sorry for raising an issue, I see whats happening now, I did
download what I thought was a deployment release zip v2.0.0-beta2
https://github.com/quickapps/cms/archive/2.0.0-beta2.zip then ran
composer update. but I see that's referencing dev repo.

On Tue, Sep 6, 2016 at 8:12 AM, Christopher Castro <notifications@github.com
