### ISSUE TITLE
List type fields

### ISSUE THREAD

**Issue by paulrwest** [quickapps/cms#168]
The instructions for List Type options states:

> The label is optional: if a line contains a single string, it will be used as key and label.

I found that this is not true if you only use one string null is saved in the value if you use the key|label format it works correctly

**Comment by botchris** [comment]
Are you using Windows?
Seems like there is a problem related to carriage return symbol on Windows ("\n\r") OS

**Comment by paulrwest** [comment]
yes I am on windows

On Wed, Nov 2, 2016 at 9:04 PM, Christopher Castro <notifications@github.com

**Comment by botchris** [comment]
please confirm this patch 64c200a326daff57ab7eeec6badf9336358d30f1 solves the problem.

**Comment by paulrwest** [comment]
Yes solved! thank you
