### ISSUE TITLE
content_revisions 'data' column needs to be LONGTEXT

### ISSUE THREAD

**Issue by paulrwest** [quickapps/cms#169]
If a content type has more than 25 fields an afterSave error is thrown on content edit due to the revision data being incorrect format and the object not getting created correctly

To resolve this I changed the field type of content_revisions data from TEXT to TEXTLONG

I understand there is a small performance hit increasing the column type and 25+ fields is an unusual scenario but it is a scenario we have hit.

**Comment by botchris** [comment]
Sounds reasonable, I'll take a look

**Comment by botchris** [comment]
Solved, `data` is now of "blob" type.

https://github.com/quickapps/cms/blob/2.0/plugins/Installer/config/fixture/ContentRevisionsFixture.php#L80
