### ISSUE TITLE
 Call to undefined function Search\Engine\Generic\iconv()

### ISSUE THREAD

**Issue by cercos** [quickapps/cms#177]
Running the installer, everything goes good until the user creation, upon which the error in the title appears after clicking create.

CakePHP 3.4.5

**Comment by botchris** [comment]
You must enable the `iconv` PHP extension.

I think I forgot to add this checking to the installer's requirements step as installation should not continue if this extension is missing on your server.

Let me know if this solves the problem.
Regards!

**Comment by cercos** [comment]
Yes that was the problem

**Comment by botchris** [comment]
Solved at de828c86c084077322909a29328a392411e79ad3
