### ISSUE TITLE
Image upload no longer working

### ISSUE THREAD

**Issue by paulrwest** [quickapps/cms#178]
After updating to latest package releases the image upload functionality seems to have stopped working. You can also see the behaviour on your demo site. 

It used to use a JS ajax system that sent the file to another function in the background. That seems to have disappeared leaving a standard upload input type but the file is not actually uploaded or saved on creating new content.  There are no errors shown or missing JS files so not sure if this was an intended change but is not actually working?

We were hooking into the ajax upload method to upload files to a CDN so would prefer that mechanism to be brought back in.

**Comment by botchris** [comment]
I'll take a look, thanks for reporting

**Comment by botchris** [comment]
For what I see it seems to be some problem with `uploadify` JS library. Their [demo upload page](http://www.uploadify.com/demos/) does not work as well.

I'll keep looking

**Comment by botchris** [comment]
Ok, so after a while I found it was Chrome blocking all flash media. Here some hints on how to allow flash in Chrome: https://helpx.adobe.com/flash-player/kb/enabling-flash-player-chrome.html

***

It seems to work ok even at demo site:

![image](https://user-images.githubusercontent.com/749463/28135304-00b3e43a-6746-11e7-835f-8e9fc2ec6b7e.png)

**Comment by paulrwest** [comment]
Ahhh thanks for spotting that! Yeah quite a few updates in the new Chrome. How much work would it be to switch to their HTML 5 version? As flash really is dead and buried.
