### ISSUE TITLE
facing error 500 while installation

### ISSUE THREAD

**Issue by nrj4all** [quickapps/cms#180]
facing error 500 after entering database credentials

ROOT/logs/errors.log:
2017-09-28 13:47:17 Error: Fatal Error (256): [Cake\Error\FatalErrorException] Theme "" was not found
#0 [ROOT]/vendor/quickapps-plugins/cms/src/Error/ExceptionRenderer.php(32): theme()
#1 [ROOT]/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(136): CMS\Error\ExceptionRenderer->__construct(Object(Cake\Error\FatalErrorException))
#2 [ROOT]/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(187): Cake\Error\ErrorHandler->_displayException(Object(Cake\Error\FatalErrorException))
#3 [ROOT]/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(225): Cake\Error\BaseErrorHandler->handleException(Object(Cake\Error\FatalErrorException))
#4 [ROOT]/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(133): Cake\Error\BaseErrorHandler->handleFatalError(256, '[Cake\\Error\\Fat...', '/usr/share/ngin...', 149)
#5 [internal function]: Cak in [[ROOT]/vendor/cakephp/cakephp/src/Error/ErrorHandler.php, line 149]

**Comment by nrj4all** [comment]
$ php -v
PHP 5.6.30-0+deb8u1 (cli) (built: Apr 14 2017 16:20:58) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies


$ nginx -v
nginx version: nginx/1.6.2

**Comment by botchris** [comment]
If this occur after a fresh installation please make sure that the Database was correctly populated, as it may be related to some bug during the installation process.

However, try clearing your all temp files at `/tmp`. Looks like your `snapshot.php` file is corrupted/malformed.

**Comment by nrj4all** [comment]
Thx for your reply. I tried as suggested but that did not worked for me. I figured out that I've used dots the database name. That caused the error.

**Comment by botchris** [comment]
I think we can restrict which characters are valid as database name during installation.

**Comment by nrj4all** [comment]
nice .. basically it is a bad style to use dot in database/table/field names due to the dot-notation.

SELECT * FROM **this.is.my.database**.table;
