### ISSUE TITLE
Error 500 after finished installing

### ISSUE THREAD

**Issue by LeLuyen** [quickapps/cms#185]
Hi There,
I have problem when finished installing and go to front-end or back-end page.
I have deleted the cache in the /tmp folder but it doesn't work.

`This page isn’t working
127.0.0.1 is currently unable to handle this request.
HTTP ERROR 500`

XAMPP: V3.2.2
Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/5.6.30
OS: Window 7.

**Comment by botchris** [comment]
We would need more information. Check your error logs at `/logs/error.log` and see what is happening.

**Comment by LeLuyen** [comment]
Hi Chris,

Here are the logs.

`2018-02-26 09:21:42 Warning: Warning (2): mkdir(): File exists in [C:\xampp\htdocs\ducthinh\vendor\goaop\framework\src\Instrument\ClassLoading\CachePathManager.php, line 83]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
mkdir - [internal], line ??
Go\Instrument\ClassLoading\CachePathManager::__construct() - ROOT\vendor\goaop\framework\src\Instrument\ClassLoading\CachePathManager.php, line 83
Go\Core\GoAspectContainer::Go\Core\{closure}() - ROOT\vendor\goaop\framework\src\Core\GoAspectContainer.php, line 122
Go\Core\Container::Go\Core\{closure}() - ROOT\vendor\goaop\framework\src\Core\Container.php, line 65
Go\Core\Container::get() - ROOT\vendor\goaop\framework\src\Core\Container.php, line 87
Go\Core\AspectKernel::registerTransformers() - ROOT\vendor\goaop\framework\src\Core\AspectKernel.php, line 237
Go\Core\AspectKernel::init() - ROOT\vendor\goaop\framework\src\Core\AspectKernel.php, line 115
require_once - ROOT\vendor\quickapps-plugins\cms\config\bootstrap_site.php, line 280
require - ROOT\vendor\quickapps-plugins\cms\config\bootstrap.php, line 18
[main] - ROOT\webroot\index.php, line 27



2018-02-26 09:21:52 Warning: Warning (2): mkdir(): File exists in [C:\xampp\htdocs\ducthinh\vendor\goaop\framework\src\Instrument\Transformer\WeavingTransformer.php, line 278]
Request URL: /
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
mkdir - [internal], line ??
Go\Instrument\Transformer\WeavingTransformer::saveProxyToCache() - ROOT\vendor\goaop\framework\src\Instrument\Transformer\WeavingTransformer.php, line 278
Go\Instrument\Transformer\WeavingTransformer::processSingleClass() - ROOT\vendor\goaop\framework\src\Instrument\Transformer\WeavingTransformer.php, line 151
Go\Instrument\Transformer\WeavingTransformer::transform() - ROOT\vendor\goaop\framework\src\Instrument\Transformer\WeavingTransformer.php, line 99
Go\Instrument\Transformer\CachingTransformer::processTransformers() - ROOT\vendor\goaop\framework\src\Instrument\Transformer\CachingTransformer.php, line 121
Go\Instrument\Transformer\CachingTransformer::transform() - ROOT\vendor\goaop\framework\src\Instrument\Transformer\CachingTransformer.php, line 78
Go\Instrument\ClassLoading\SourceTransformingLoader::transformCode() - ROOT\vendor\goaop\framework\src\Instrument\ClassLoading\SourceTransformingLoader.php, line 136
Go\Instrument\ClassLoading\SourceTransformingLoader::filter() - ROOT\vendor\goaop\framework\src\Instrument\ClassLoading\SourceTransformingLoader.php, line 103
Go\Instrument\ClassLoading\AopComposerLoader::loadClass() - ROOT\vendor\goaop\framework\src\Instrument\ClassLoading\AopComposerLoader.php, line 139
Go\Instrument\ClassLoading\AopComposerLoader::loadClass() - ROOT\vendor\goaop\framework\src\Instrument\ClassLoading\AopComposerLoader.php, line 139
spl_autoload_call - [internal], line ??
class_exists - [internal], line ??
Cake\Core\ObjectRegistry::load() - CORE\src\Core\ObjectRegistry.php, line 92
Cake\View\View::loadHelper() - CORE\src\View\View.php, line 1228
Cake\View\View::loadHelpers() - CORE\src\View\View.php, line 1129
Cake\View\View::__construct() - CORE\src\View\View.php, line 364
CMS\View\View::__construct() - APP/View\View.php, line 82
Cake\View\ViewBuilder::build() - CORE\src\View\ViewBuilder.php, line 629
Cake\Controller\Controller::createView() - CORE\src\View\ViewVarsTrait.php, line 121
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 622
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 125
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 60
[main] - ROOT\webroot\index.php, line 37
`
Thanks you!

**Comment by botchris** [comment]
Seems like incorrect read/write permissions. Check that QACMS is able to write (and read) on `tmp` (recursively)

**Comment by LeLuyen** [comment]
Hi Chris,

I don't think so.

On the win7 OS, I checked the `tmp` folder with the permission is 777.

I think the AOP have problem!

**Comment by LeLuyen** [comment]
Hi Chris,

[Tue Mar 13 17:26:08.723168 2018] [:error] [pid 5556:tid 1632] [client ::1:58295] PHP Fatal error:  Class 'Cake\\Datasource' not found in C:\\xampp\\htdocs\\site\\vendor\\cakephp\\cakephp\\src\\Datasource\\QueryTrait.php on line 380
[Tue Mar 13 17:26:08.724168 2018] [:error] [pid 5556:tid 1632] [client ::1:58295] PHP Fatal error:  Class 'Cake\\Error\\Debugger' not found in C:\\xampp\\htdocs\\site\\vendor\\cakephp\\cakephp\\src\\Error\\BaseErrorHandler.php on line 278

**Comment by botchris** [comment]
Seems like a problem with class autoloading.

- what version of QACMS are you using?
- did you install it using `composer`?
- is `mod_rewrite` enabled?

**Comment by LeLuyen** [comment]
Hi Chris,

1. I'm using the latest version of QACMS.

2. yes.

3. yes.

Thanks you!

**Comment by LeLuyen** [comment]
Hi Chris,

On the https://github.com/quickapps/cms/blob/2.0/composer.json link, the requirement of cakephp version is 3.3.11 but when run `composer create-project -s dev quickapps/website [website_name]` the cakephp version is latest. Is it the root cause?

Thank you!

**Comment by quickapps** [comment]
Fixed here: https://github.com/quickapps/website/commit/264d08d2e69796650be483202d41f2d1960af8d6

(QACMS is installed using `quickapps/website` repo as project skeleton)

**Comment by LeLuyen** [comment]
Hi Chris,

i'm trying, but don't work ):

Debug log:

2018-04-05 14:55:08 Notice: Notice (8): Undefined offset: 1 in [/var/www/html/quickapps/vendor/cakephp/cakephp/src/Network/Response.php, line 641]
Request URL: /quickapps/
Referer URL: http://127.0.0.1/quickapps/installer/startup/finish?locale=en_US
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
Cake\Network\Response::header() - CORE/src/Network/Response.php, line 641
CMS\Controller\Controller::__construct() - APP/Controller/Controller.php, line 82
ReflectionClass::newInstance() - [internal], line ??
Cake\Http\ControllerFactory::create() - CORE/src/Http/ControllerFactory.php, line 79
Cake\Routing\Filter\ControllerFactoryFilter::_getController() - CORE/src/Routing/Filter/ControllerFactoryFilter.php, line 63
Cake\Routing\Filter\ControllerFactoryFilter::beforeDispatch() - CORE/src/Routing/Filter/ControllerFactoryFilter.php, line 49
Cake\Routing\DispatcherFilter::handle() - CORE/src/Routing/DispatcherFilter.php, line 144
Cake\Event\EventManager::_callListener() - CORE/src/Event/EventManager.php, line 426
Cake\Event\EventManager::dispatch() - CORE/src/Event/EventManager.php, line 391
Cake\Http\ActionDispatcher::dispatchEvent() - CORE/src/Event/EventDispatcherTrait.php, line 78
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 80
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 60
[main] - ROOT/webroot/index.php, line 37

Error log:

2018-04-05 14:55:13 Error: Fatal Error (1): Class 'Cake\Datasource' not found in [/var/www/html/quickapps/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php, line 368]
Request URL: /quickapps/en_US/find/type:article
Referer URL: http://127.0.0.1/quickapps/
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??



2018-04-05 14:55:17 Error: Fatal Error (1): Class 'Cake\Datasource' not found in [/var/www/html/quickapps/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php, line 368]
Request URL: /quickapps/en_US/find/type:article
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??



2018-04-05 14:55:20 Error: Fatal Error (1): Class 'Cake\Datasource' not found in [/var/www/html/quickapps/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php, line 368]
Request URL: /quickapps/en_US/find/type:article
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??



2018-04-05 14:55:23 Error: Fatal Error (1): Class 'Cake\Datasource' not found in [/var/www/html/quickapps/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php, line 368]
Request URL: /quickapps/en_US/find/type:article
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 98
[main] - [internal], line ??

PHP 5.6.11-1ubuntu3.4 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

Server version: Apache/2.4.12 (Ubuntu)
Server built:   Jul 15 2016 15:32:10
Mysql version: 5.6.31-0ubuntu0.15.10.1

**Comment by botchris** [comment]
Here is the cause I think: https://github.com/goaop/parser-reflection/issues/80

**Comment by LeLuyen** [comment]
Hi Chris,

Yes, it works

Thank you
