### ISSUE TITLE
Do you need Filipino Translation for your CMS?

### ISSUE THREAD

**Issue by josephbuarao** [quickapps/cms#186]
Hi there,

Good day and how are you? I hope this message finds you well.

I am Joseph Buarao ,  who has been doing high quality Filipino and Tagalog translations for several projects.

Consider this message as my letter of application. I am a web developer by profession and an experienced Utopian translator -these are on top of being an experienced web developer with more than 6 years of experience and specialized in the following scripting languages and technologies (HTML, CSS, JS, JQUERY, PHP, WORDPRESS and CONCRETE5). This means I know which codes are to be translated, and which ones that are to remain as it is. I am a strong advocate of thought-by-thought instead of word-by-word style of doing the translations, and I am carefully strict in grammars and spellings and proper word conjugations of my languages, Filipino and Tagalog. 

I hope to hear from you soon and work with you in the translations. You can count on me that I will do my job with utmost dedication. Thank you and more power to you.

Best Regards,
Joseph Buarao

**Comment by botchris** [comment]
I'm pretty glad to hear this. Contributions are always welcome on this project!

Feel free to contact if you need further information about how to proceed.

**Comment by josephbuarao** [comment]
Hi Cristopher, 

Thank you for your quick reply. Could you please provide information how to proceed. I am happy to start as soon as possible.

Thank you!

**Comment by botchris** [comment]
# How to translate

1. Fork this repo.
2. Identify your language code, e.g. `es` (*)
3. For each plugin's `src/Locale/` directory, create a subdirectory using your language code. e.g. `src/Locale/es/`
4. Use the Portable Object Template (pot file extension) located at `src/Locale/` of every plugin.
5. Translate and save the resulting `.pot` file in the subdirectory at step 3. (the name of the pot file must be the lowercased_underscored plugin's name, e.g. `src/Locale/es/cms.pot`)
6. Create a pull-request to this repo to merge your work.

(*) You can use general 3-letter codes (like eng) or more location specific codes (like en_US).

***

Example: https://github.com/quickapps/cms/tree/2.0/plugins/Installer/src/Locale

**Comment by josephbuarao** [comment]
Thank you Christopher! I will work on it.
