### ISSUE TITLE
Shell issue on Theme generation

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#23]
Fresh new installation and last code of shell script package.

When I run the shell and I choose to make a Theme I receive a stack trace as shown below:
## Welcome to CakePHP v2.1.0-dev Console

App : app
## Quickapps CMS - Shell
1. Module shell
2. Themes shell
3. Utility shell
4. Quit
   What would you like to do (1/2/3/4) 
   > 2
   Quickapps CMS - Themes
   ---------------------------------------------------------------
   Notice Error: Undefined property: ThemeTask::$Gui in [/home/gabri/workspace/uacepquickapp/app/Cake/Console/Shell.php, line 440]

PHP Fatal error:  Call to a member function menu() on a non-object in /home/gabri/workspace/uacepquickapp/app/Plugin/System/Console/Command/Task/ThemeTask.php on line 12
PHP Stack trace:
PHP   1. {main}() /home/gabri/workspace/uacepquickapp/app/Cake/Console/cake.php:0
PHP   2. ShellDispatcher::run() /home/gabri/workspace/uacepquickapp/app/Cake/Console/cake.php:24
PHP   3. ShellDispatcher->dispatch() /home/gabri/workspace/uacepquickapp/app/Cake/Console/ShellDispatcher.php:69
PHP   4. Shell->runCommand() /home/gabri/workspace/uacepquickapp/app/Cake/Console/ShellDispatcher.php:177
PHP   5. QuickappsShell->main() /home/gabri/workspace/uacepquickapp/app/Cake/Console/Shell.php:389
PHP   6. GuiTask->menu() /home/gabri/workspace/uacepquickapp/app/Plugin/System/Console/Command/QuickappsShell.php:25
PHP   7. ThemeTask->main() /home/gabri/workspace/uacepquickapp/app/Plugin/System/Console/Command/Task/GuiTask.php:51

**Comment by quickapps** [comment]
I forgot to include the Gui task,
Fixed here:
https://github.com/QuickAppsCMS/QuickApps-CMS-CLI/commit/9949fefe135b11762bb6fb54caf3d5a75434c5fb

Thanks!
Chris
