### ISSUE TITLE
Radio buttons and checkboxes does not remember their settings

### ISSUE THREAD

**Issue by hachesilva** [quickapps/cms#28]
How to reproduce the issue: Create a radiobutton or checkbox field in any content type, give it at least 2 options. Then, create an item of that content type and fill the radiobutton field choosing any option. Save it. Then, edit the created item. The choosed value for the field isn't there.

What should happen: The content type should save the checkboxes / radiobutton states when saved and retrieve them when you try to edit them.

**Comment by quickapps** [comment]
I'll take a look,
thanks!
