### ISSUE TITLE
DebugKitHookComponent issue

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#31]
Fresh new installation from github of QACMS, and added some modules (from github) correctly.
When I uploaded the DebugKit module (it was checked the "active after installation") I had this blocking error:
Fatal error: Call to a member function is() on a non-object in /dati/server/home/guidi/qa/Modules/DebugKit/Controller/Component/DebugKitHookComponent.php on line 4

**Comment by quickapps** [comment]
Fixed here:
https://github.com/QuickAppsCMS/QACMS-DebugKit/commit/047651d9cdccfc7cee5c5ad0672ae2650e8e4645

Thanks!

P.S.: In order to keep things in order, please, for module related issues use the issue-tracker system of the corresponding module.

**Comment by Gabri** [comment]
Perfect, you're right!
