### ISSUE TITLE
User mailing notification: default fields bodys are shown empty

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#32]
I've encountered a strange thing.
When I go on admin/system/modules/settings/User I could see the default "subject" values but not the "body" ones.
On database these fields are not empty (or "false" as they are on the view).
Saving some data on theme works fine

**Comment by quickapps** [comment]
You will have to manually fix your data base.
Windows use CRLF while Linux (and gitGui) use LF for linebreaks.

See the commit below for information about how to fix it.
