### ISSUE TITLE
Module installation (of the zipped one packaged from shell script)

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#33]
I've just created a Module (AddThis), it was packed in 
/server/home/guidi/qa/webroot/files/AddThis.zip
I tried to install from backoffice, and doing this i had this blocking error for the entire website:

Missing Component
Error: .ModuleNameHookComponent could not be found.
Error: Create the class .ModuleNameHookComponent below in file: /dati/server/home/guidi/qa/Controller/Component/.ModuleNameHookComponent.php
<?php
class .ModuleNameHookComponent extends Component {

}
Notice: If you want to customize this error message, create /dati/server/home/guidi/qa/View/Errors/missing_component.ctp
Stack Trace
APP/Cake/Controller/ComponentCollection.php line 52 → ComponentCollection->load(string, array)
APP/Cake/Controller/Controller.php line 611 → ComponentCollection->init(ModulesController)
APP/Cake/Routing/Dispatcher.php line 100 → Controller->constructClasses()
APP/Cake/Routing/Dispatcher.php line 86 → Dispatcher->_invoke(ModulesController, CakeRequest, CakeResponse)
CORE/qa/webroot/index.php line 47 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by Gabri** [comment]
Maybe it's just a problem with Mac dotted file generated...
I'll try with a different server, maybe it's just a problem of this particular environment

**Comment by Gabri** [comment]
Yes, on my local pc no problem. Tomorrow I'll try in the same server to uderstand better the problem.
So probably not a bug

**Comment by quickapps** [comment]
I think this can be related to the Hook-preloader logic,

System.Lib/HookCollection.php
find the line 351:

```
   $files = $folder->find('(.*)Hook(Component|Behavior|Helper|tagsHelper)\.php');
```

replace for this one:

```
   $files = $folder->find('([a-zA-Z0-9]*)Hook(Component|Behavior|Helper|tagsHelper)\.php');
```

That should ignore any class file containing non-alphanumeric chars on its name.

then clear your cache files on `tmp/cache` and try again

**Comment by Gabri** [comment]
yes, that perfectly solves the problem!
