### ISSUE TITLE
New Installation issue

### ISSUE THREAD

**Issue by linuxusr** [quickapps/cms#34]
Hello,

When unpacking the tarball, it doesn't seem like there is an index file for the installation. Am I missing something here?

Thanks in advance,

**Comment by Gabri** [comment]
yes, it's right.
There is an .htacces file that point on the right position. Be sure that mod_rewrite is enabled.
you just need to point your virtualhost (or similar) on that folder as the root of the website ...and just access it with browser

**Comment by quickapps** [comment]
As Gabri said, make sure that mod_rewrite is enabled.

If you need help, just write on google group (https://groups.google.com/group/quickapps-cms) and we'll be glad to help you.
