### ISSUE TITLE
$node['Node']['comment_count'] not updated

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#35]
QACMS 1.0RC3 (not last from github)
it seems that the $node['Node']['comment_count'] it is always set to "1" (theme_node.ctp)
If I add a new article it indicates:
"published by admin on Mar 08, 2012 16:37 | 1 comments"
If I Add new 5 comments ...it always says that there is 1 comment (I don't think it's a cache problem)

**Comment by quickapps** [comment]
That was fixed a few days ago:
https://github.com/QuickAppsCMS/QuickApps-CMS/commit/499737a5c87dc44f8c4eafa0f06fd911cbac9403
