### ISSUE TITLE
search content

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#40]
I'm not really sure it's an issue or a specific implementation choice.
The nodes' content body (article, basic page...) is not searchable (http://cms.quickapps.es/s/Configurable doesn't show any result but 'Configurable' is present on the main content of the last post).
Title, slug and description are searchable fields (of Node table), but not the main content (on Field Data table).

I can see these fields on the query ...even if I cannot have the aspected result looking for a word present only on the node.description field. It doesn't seem to work (http://cms.quickapps.es/s/System - 'System' seems to be present in your description field posts).
Another field not considered in the search action is the content Introduction (http://cms.quickapps.es/s/Finally doesn't show any result).

I think that at least the node main content should be searchable.
Maybe it could be interesting to search on even terms too (if it's not a big problem for performance).

**Comment by quickapps** [comment]
This is a "limitation" of QuickApps CMS.
This occurs because Field's data is fetched to each node after node's find action.
And because field's entities are not a homogeneous structure.
e.g.: Some fields may not use the `field_data` table. Even more, some fields may define its own "storage system", and that storage system can be even an other data base or table.

I have some solutions in mind for that, but API changes will be required. So I'll put this to the future v1.1.

**Comment by Gabri** [comment]
I see.
Why not include the main content (body, and maybe introduction field too) as field of the node table?
I think it is a basic field data. Field API is a fantastic tool, but I think more for extendable features than basic data.
If it was on the node table it would be searchable easely and we would have an increasing of performance too.
A bit tedious for upgrading existing content to this eventually new version of QACMS...
What do you think? Bad idea?

**Comment by quickapps** [comment]
Nodes are polymorphic.
There may be some nodes that doesn't have a body, or an intro input.
A data must be part of every node to be considered "basic", so those fields (body, intro) are not "basic" at all.

The solution for this is to create an extra table schema, which holds all searchable words that a node has.
To fix previous content all what you will have to do is simply save again each node (edit form), and not so tedious as you may be thinking.

---

As we are only a few who use QuickApps CMS right now, I think that I can include this feature as part of the actual 1.0 and re-tag it.

**Comment by Gabri** [comment]
I see.
For my first QA website it will not be a problem this current search behavior, but it could be for the next one (not too soon. it will be multilingual too, so it should be searchable in any language; but I think the implementation you've suggested will cover this issue because every translation belongs to a specific node).
Do what you think is best, it could be introduced in the v1.1 too, no problem

**Comment by Gabri** [comment]
Thank you very much, Chris. It works everything fine!
