### ISSUE TITLE
An Internal Error Has Occurred 

### ISSUE THREAD

**Issue by dxd1** [quickapps/cms#5]
I get the error message: "An Internal Error Has Occurred
Error: An Internal Error Has Occurred. " 
It's after filling out the database info.
Only qa_acos table is created. It's last row is:
151 141         my_account  299 300

**Comment by quickapps** [comment]
- Set your debug level to 2.
- Check your logs files in ./tmp/logs.

I have tested a fresh install in different servers and all them seems to work fine.
This may be caused by some server incompatibility or restriction.

Show me your `./tmp/logs/error.log` file, so I can try to fix it.

**Comment by dxd1** [comment]
2011-11-30 09:09:39 Error: [PDOException] SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
#0 D:\wamp\www\quickapps\app\Cake\Model\Datasource\DboSource.php(436): PDOStatement->execute(Array)
#1 D:\wamp\www\quickapps\app\Cake\Model\Datasource\DboSource.php(403): DboSource->_execute('?/_!40101 SET @...', Array)
#2 D:\wamp\www\quickapps\app\Controller\InstallController.php(179): DboSource->execute('?/_!40101 SET @...')
#3 [internal function]: InstallController->database()
#4 D:\wamp\www\quickapps\app\Cake\Controller\Controller.php(473): ReflectionMethod->invokeArgs(Object(InstallController), Array)
#5 D:\wamp\www\quickapps\app\Cake\Routing\Dispatcher.php(107): Controller->invokeAction(Object(CakeRequest))
#6 D:\wamp\www\quickapps\app\Cake\Routing\Dispatcher.php(89): Dispatcher->_invoke(Object(InstallController), Object(CakeRequest), Object(CakeResponse))
#7 D:\wamp\www\quickapps\webroot\index.php(49): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}

**Comment by quickapps** [comment]
This is probably an issue of your PHP version.
¿What version of PHP & MySQL are you using?

I just tested locally a fresh install using _WAMP 2.2_ and all seems to be ok.
So I cannot reproduce this issue even using wamp like you.

Anyway, modify this file **_app/Controller/InstallController.php_** and try to install QuickApps again:

find the line:

```
  $execute[] = $db->execute(str_replace('#__', $data['Database']['prefix'], $query));
```

and add this new line just after:

```
 $db->reconnect();
```

So your code should looks:

```
   ....
    foreach ($files as $sql_file) {
        $file = new File(APP . 'Config' . DS . 'Schema' . DS . 'tables' . DS . $sql_file);
        $sql = $file->read();
        $query = $this->__prepareDump($sql);
        $execute[] = $db->execute(str_replace('#__', $data['Database']['prefix'], $query));

        $db->reconnect(); // add this line
    }
   ....
```

**Comment by dxd1** [comment]
I use PHP 5.2.6 and MySQL 5.0.51b
The reconnect solved the problem, Quickapps installed without any error this way.
Thank you for your help and for the great product!
