### ISSUE TITLE
strange behavior on a custom content type

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#52]
Hi,

QACMS v1.1, but i have the same behavior on the demo site.

I created a "faq" content type (with id and name = 'faq'), with two simple field text: question and answer (255 max width).
if the id is "faq" when i list the content (/s/type:faq) the content is shown but if I click on the title (or Read More link) a blank page is shown (at home with v1.1 it redirect me on the home  page) with the url: faq/faq-1.html.
If i change the id of the content type to, for example, 'faq_example', it ...works:
/s/type:faq_example list the content and clicking on the tile or read more link it opens correctly the page: faq_example/faq-1.html

There is an example on demo page too (I've restored the id in 'faq', that raises the problem):
http://demo.quickapps.es/eng/s/type:faq
http://demo.quickapps.es/faq/faq-1.html (the problematic page)

**Comment by Gabri** [comment]
ps.: maybe the problem is derived by the same name: id and name

**Comment by quickapps** [comment]
**faq**/faq-1.html
I think it's a language prefix conflict

**Comment by Gabri** [comment]
Mmm, yes ...the three chars ...I make some tests

**Comment by quickapps** [comment]
Here is the problem,
Router.php:

```
if (!preg_match('/^\/[a-z]{3}\//', $output)) {
    $output = '/' . Configure::read('Config.language') . $output;
}
```

As `faq/faq-1.html` already start by 3 chars, no language prefix is prepend to it.
It should be `/xxx/faq/faq-1.html`

[1] One solution to this is cache all the valid languages to perform a better preg_match rule. This may reduce the conflict possibilities....But for example, if you create a Content type named `eng` ...then the issue will appear.

I'll try to think a better solution than [1] to completely avoid this.

**Comment by quickapps** [comment]
The simplest solution is to make Content Type's name be 4 chars min required.

I dont't really like much this, but it is the most simple of the solutions available. :S

So instead "faq" you should use "faqs"

---

EDIT:
Other solution is this ugly patch:

```
 if (!preg_match('/^\/[a-z]{3}\//', $output) || preg_match('/^\/[a-z]{3}\/.*\.html/', $output)) {
     $output = '/' . Configure::read('Config.language') . $output;
 }
```

**Comment by Gabri** [comment]
Yes, absolutely. No problem for now, it's enough understanding the problem. Take your time to think a simple solution

**Comment by Gabri** [comment]
...or just deny a content Type with less than 4 chars  :)

**Comment by quickapps** [comment]
Yes, I'll do this last...until I look for a better solution.
