### ISSUE TITLE
Problem on Theming Nodes by Content Type

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#54]
QACMS v1.1 (sources from two days ago ...more or less)

I tried to theme an individual content type, a custom type created by me.
I cannot make it work, so I try to understand why.
In NodeHookHelper.php > node_render($node)  -> $nodeType remains == false
so it doesn't try to get my file.
I think the previous if are not completed.
$node['Node']['node_type_id'] or $node['NodeType']['id'] have the right value...

**Comment by quickapps** [comment]
I was unable to reproduce this issue on my local installation.
I've created a `faqs` content-type and then created `theme_node_faqs.ctp` and all seems to be okay.
- What is the ID of your content_type ?
- And the name of your .ctp file?

**Comment by Gabri** [comment]
First, a my mistake: I thought that in this way I could override also the LIST of a specific node type, not just the node redering.
So the "false" result was on listing that content (<code>/s/type:example _ type</code> ...there is no spaces betweend underscore char ...but otherwise the editor remove it)
Anyway, showing the specific content I have a problem too.
Strange, the <code>file_exists($tp . 'Elements' . DS . 'theme_node_' . $nodeType . '.ctp')</code> return false, but I put the file in the same folder of <code>theme_node.ctp</code> and its name is <code>theme_node_example_type.ctp</code>.
I tried this line:
<code>debug(file_exists($tp . 'Elements' . DS . 'theme_node_node.ctp'));</code>
and it is false too... (but I have that file and it works)

**Comment by quickapps** [comment]
Exactly, the node theming feature is for the "FULL" view mode only (node's detail page)

---

Well the result of ´file_exists()´ is very clear. Check that your .ctp file is located where it should:

```
 debug($tp . 'Elements' . DS . 'theme_node_' . $nodeType . '.ctp');
```

Instead checking the return of the function, make sure that the argument (file path) is correct and exists in your computer,
It should be:

```
   /absolute_path/to/your_active_theme/Elements/theme_node_example_type.ctp
```

**Comment by quickapps** [comment]
After thinking a bit, I think thi is incorrect:
"Exactly, the node theming feature is for the "FULL" view mode only (node's detail page)"

This ferature should simply acts as an alternative `theme_node.ctp` file. So it should work for any view mode, just as you were thinking at the begining.

---

I've removed the `$this->is('view.node')` part, because the same .ctp file may be used for any view mode. Similar as `theme_node.ctp` works:

https://github.com/QuickAppsCMS/QuickApps-CMS/commit/c5e606a99b16caee6999ebea3a0c4ed657676ffb

**Comment by Gabri** [comment]
Great!
It think it's correct behavior too!
My mistake for the file ...I was trying on another installation with the same Theme...
