### ISSUE TITLE
Problem accessing /contact for anonymous users + typo

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#56]
Fresh new installation QACMS v1.1
I installed QuickContact, I tried to go to /contact page (with a different browser) and I was forwarded to the login page because I wasn't authorized.
So I went on /admin/user/permissions and I check on all the records of "Use the site-wide contact form" (by default just administrator could go there) ...but even if all are authorized to go there I have always the same result (login page and the error flash message).
I tried clean cache, add permissions also to "Use users' personal contact forms"... but I cannot access to /contact
I tried also to access to /contact/gabri ...the same result.

With admin user logged I have access to the contact page, but if I try to fill the form and send message I have a blank page with:
<code>Notice (8): Undefined property: View::$Layout [APP/Cake/View/View.php, line 804] Fatal error: Call to a member function meta() on a non-object in
/home/gabri/workspace/qa3/Themes/Themed/qaTheme/Layouts/error.ctp on line 6 Call Stack: 0.2099 4466548 1. ErrorHandler::handleException()
/home/gabri/workspace/qa3/QuickApps/Cake/Error/ErrorHandler.php:0 0.2424 4664236 2. ExceptionRenderer->render()
/home/gabri/workspace/qa3/QuickApps/Cake/Error/ErrorHandler.php:127 0.2424 4664788 3. call_user_func_array()
/home/gabri/workspace/qa3/QuickApps/Cake/Error/ExceptionRenderer.php:165 0.2424 4664816 4. ExceptionRenderer->_cakeError()
/home/gabri/workspace/qa3/QuickApps/Cake/Error/ExceptionRenderer.php:0 0.2425 4666080 5. ExceptionRenderer->_outputMessage()
/home/gabri/workspace/qa3/QuickApps/Cake/Error/ExceptionRenderer.php:187 0.2742 6850828 6. ExceptionRenderer->_outputMessageSafe()
/home/gabri/workspace/qa3/QuickApps/Cake/Error/ExceptionRenderer.php:267 0.2742 6851788 7. Controller->render()
/home/gabri/workspace/qa3/QuickApps/Cake/Error/ExceptionRenderer.php:285 0.2854 7010212 8. View->render()
/home/gabri/workspace/qa3/QuickApps/Cake/Controller/Controller.php:962 0.2967 7206848 9. View->renderLayout()
/home/gabri/workspace/qa3/QuickApps/Cake/View/View.php:471 0.2972 7208192 10. View->_render() /home/gabri/workspace/qa3/QuickApps/Cake/View/View.php:527
0.2974 7208080 11. View->_evaluate() /home/gabri/workspace/qa3/QuickApps/Cake/View/View.php:872 0.2975 7265100 12.
include('/home/gabri/workspace/qa3/Themes/Themed/qaTheme/Layouts/error.ctp') /home/gabri/workspace/qa3/QuickApps/Cake/View/View.php:908</code>

---

There is a typo on php and default.pot and the corrisponding php:
Max lenght --> Max length
Plugin\Field\Fields\FieldText\View\Elements\settings_form.ctp:75

**Comment by quickapps** [comment]
I was unable to reproduce the blank page, maybe it was related to the same permission issue.
Check if now works.

**Comment by Gabri** [comment]
The authentication now works fine!
But when I send the form I always have the blank page with the message above.
Maybe could be related to the fact that I'm on a localhost?
Transport now it's set on PHP mail() function

**Comment by Gabri** [comment]
Other thing: I noted that the form labels weren't traslated. They are not present on default.pot (even if one entry is present because is the same in the comment form: "Your name *"), probably because it is specifically indicated the domain "quick_contact". I imagine I can add a specific default.po in the Locale folder (in the sub folder of the languages related)  of QuickContact Module

**Comment by quickapps** [comment]
non-core modules always use its domain for translations,
default.pot is aimed to translate Core entries only. Use core's default.po to translate all is not really a good practice.
That is why QA allows you to attach a .po package to an especific module in the packages section (/admin/locale/packages)

---

Using SMTP mail transport fails too ?
I'm not sure but, can this be related to your `qaTheme`, try changing to core's `Default` ?

Remove this file: `/qaTheme/Layouts/error.ctp` to use the core error layout and see what is the real error.

**Comment by Gabri** [comment]
I agree regards the translation.

I think you're right, changing to the Default theme I have a simple email sending problem
<code>APP/Cake/Network/Email/CakeEmail.php line 972 → MailTransport->send(CakeEmail)...</code>
and not the problem as above.
Sorry, I try to find what break the process...

**Comment by quickapps** [comment]
Seems like your smtp server is unable to send the email.

`/admin/system/modules/settings/QuickContact`:
- if you are using php mail() function you must have a SMTP server on your machine.
- If you are using an external SMTP, check the information you entered is correct.
