### ISSUE TITLE
Internal error on /admin/node/contents

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#57]
Hi, I've update my local installation with last sources from github and on administration if I go on /admin/node/contents I have an error page:
<code>An Internal Error Has Occurred</code>

in error.log:
<code>2012-05-02 23:04:37 Error: [Exception] DateTimeZone::__construct(): Unknown or bad timezone ()
#0 /home/gabri/workspace/qatest3/QuickApps/Cake/Utility/CakeTime.php(238): DateTimeZone->__construct('')
#1 /home/gabri/workspace/qatest3/QuickApps/Cake/Utility/CakeTime.php(208): CakeTime::timezone('')
#2 /home/gabri/workspace/qatest3/QuickApps/Cake/Utility/CakeTime.php(279): CakeTime::convert(1335859091, '')
#3 /home/gabri/workspace/qatest3/QuickApps/Cake/Utility/CakeTime.php(808): CakeTime::fromString(1335859091, '')
#4 /home/gabri/workspace/qatest3/QuickApps/Cake/View/Helper/TimeHelper.php(391): CakeTime::format('d/m/Y - H:i', 1335859091, NULL, '')
#5 /home/gabri/workspace/qatest3/QuickApps/View/Helper/TableHelper.php(357) : eval()'d code(1): TimeHelper->format('d/m/Y - H:i', 1335859091, NULL, '')
#6 /home/gabri/workspace/qatest3/QuickApps/View/Helper/TableHelper.php(357): eval()
#7 /home/gabri/workspace/qatest3/QuickApps/View/Helper/TableHelper.php(299): TableHelper->__php_eval('<?php  return $...', Array)
#8 /home/gabri/workspace/qatest3/QuickApps/View/Helper/TableHelper.php(170): TableHelper->_renderCell('{php} return $t...', Array)
#9 /home/gabri/workspace/qatest3/QuickApps/View/Helper/QaHtmlHelper.php(55): TableHelper->create(Array, Array)
#10 /home/gabri/workspace/qatest3/QuickApps/Plugin/Node/View/Contents/admin_index.ctp(154): QaHtmlHelper->table(Array, Array)
#11 /home/gabri/workspace/qatest3/QuickApps/Cake/View/View.php(907): include('/home/gabri/wor...')
#12 /home/gabri/workspace/qatest3/QuickApps/Cake/View/View.php(871): View->_evaluate('/home/gabri/wor...', Array)
#13 /home/gabri/workspace/qatest3/QuickApps/Cake/View/View.php(463): View->_render('/home/gabri/wor...')
#14 /home/gabri/workspace/qatest3/QuickApps/Cake/Controller/Controller.php(959): View->render(NULL, NULL)
#15 /home/gabri/workspace/qatest3/QuickApps/Cake/Routing/Dispatcher.php(194): Controller->render()
#16 /home/gabri/workspace/qatest3/QuickApps/Cake/Routing/Dispatcher.php(162): Dispatcher->_invoke(Object(ContentsController), Object(CakeRequest), Object(CakeResponse))
#17 /home/gabri/workspace/qatest3/webroot/index.php(47): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#18 {main}</code>

**Comment by quickapps** [comment]
I was unable to reproduce this.
Anyway I can see it is caused by an empy value of this:

```
 $this->Session->read('Auth.User.timezone');
```

Does your user acount has a value on the `timezone` column of the `users` table?

---

Anyway I think this should solve the problem:
https://github.com/QuickAppsCMS/QuickApps-CMS/commit/f3862dd825180fd78ee8204e3b9987f8d9c8c4ed

(confirm to close)

more info:
Since cakephp 2.2 has a added "Config.timezone" param to configure global timezone for the application.
http://bakery.cakephp.org/articles/markstory/2012/04/30/cakephp_2_1_2_2_2_0-beta_released

**Comment by Gabri** [comment]
The <code>timezone</code> field of my user account was <code>NULL</code>, it was the admin account created during the installation.
Yes, that's resolve the problem!  :)

Thanks
