### ISSUE TITLE
warning and notice on /admin/block/manage

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#60]
Hello Chris,
I've just updated the sources of QACMS v1.1.
I've gone on /admin/block/manage and I see some notices and warnings like these:
<code>Notice (8): Undefined offset: 6 [APP/Cake/Utility/Hash.php, line 783]
Warning (4096): Argument 1 passed to Hash::extract() must be an array, null given, called in /home/gabri/workspace/stramaz3/QuickApps/Plugin/Block/View/Elements/regions.ctp on line 36 and defined [APP/Cake/Utility/Hash.php, line 89]
Warning (2): Invalid argument supplied for foreach() [APP/Cake/Utility/Hash.php, line 121]</code>
and
<code>Notice (8): Undefined index: title [APP/Plugin/Block/View/Elements/regions.ctp, line 56]</code>

**Comment by quickapps** [comment]
I was totally unable to reproduce this, but this may work:

b627e0752d578a2ec3a7c62df987b6e149ebe4a9

**Comment by Gabri** [comment]
I can try it this evening, I'll let you know. Thanks

**Comment by Gabri** [comment]
Yes, that's solve the problem! Thanks again
