### ISSUE TITLE
Double-clicking submit button submits forms twice

### ISSUE THREAD

**Issue by ataylor32** [quickapps/cms#69]
I tested this with the "Add Content" form and the "Add new comment" form. With both forms, I was able to sit there mashing the submit button over and over again, causing several duplicate submissions to occur. Granted, most people won't do that, but an average Joe _will_ double-click the submit button. JavaScript can mitigate the issue, but it should be dealt with on the server side as well.

**Comment by ataylor32** [comment]
The CSRF prevention does, indeed, prevent duplicate submissions, but it also gives the user a message that could potentially scare them:

> ## The request has been black-holed
> 
> **Error:** The requested address **'/article/example.html'** was not found.
> There are no translations available or you don't have sufficient permissions.

That's the message I got from double-clicking the "Save" button when leaving a comment—a perfectly innocent mistake that is often made by users who aren't tech-savvy. I would suggest replacing the message with a less scary one and then adding JavaScript to (1) disable the submit button once clicked and (2) add a spinner next to the button for a visual indication that their form is being submitted. You could use something like spin.js for the second part.

**Comment by quickapps** [comment]
Solution to (1): ecd718afe267580f9413db24d761abc87720371d
Im working in a automagic JS DOM based button-disabling feature.

**Comment by quickapps** [comment]
Solution to (2): 191cbd75897f37b9a95814395aa3f6de44214c0a

---

This solution does not includes the "visual indicator" next to the submit button (button invalidation). Instead, it silently discard extra submits on each form, this prevent some issues such as that Forms can be submitted without touching the submit button (pressing Enter key)

**Comment by ataylor32** [comment]
It's looking better! There are still a couple issues that you may or may not care about; I'm just letting you know just in case.

First, it looks like your black hole handler assumes that the only time a request will ever get black-holed is from duplicate content. But there are other things a legitimate user could do to trigger a black hole. For example, let's say the user performed an advanced search for something and didn't get the results they were hoping for. So they click their browser's back button, modify the advanced search form a bit, and click the "Search" button again. This would trigger a black hole and the message about duplicate content would confuse them.

The second issue is that in Firefox, when the user submits a form and then clicks their browser's back button, the form is still disabled. The workaround is to listen for the window's "pageshow" event and enable all forms that should be enabled. When would this issue ever come up? See the previous paragraph for a perfectly reasonable scenario.

**Comment by quickapps** [comment]
The black-holed handler simply assumes that there is a old token being used again by request.
What you described is just a normal behavior under an "Aggressive Security" enviroment.
A simple solution is to allow multi-use tokens (csrfUseOnce = false):
075b52fc69a3b88b397c959491214a26b1c09cce

---

I'll take a look to the second issue, previous fix doest work

Regards!

**Comment by ataylor32** [comment]
Yeah, it is normal behavior under an aggressive security environment, but usually the message is a generic one that doesn't make assumptions as to what triggered the black hole. Here's what GitHub uses:

> # There was a problem with your request.
> 
> Usually this means that your user authenticity token is incorrect. This can happen when you visit a page with a form, then sign in from a separate window, and then return to resubmit the form. Here's what you can try next:
> - Go back and refresh the page that brought you here. Make sure the toolbar shows that you're signed in.
> - If the problem persists, [contact us](http://github.com/contact) and we'll help get you on your way.

As for forms still being disabled when Firefox's back button is clicked, your solution won't work, unfortunately.
