### ISSUE TITLE
installation problem on last github version

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#7]
I've encontered a problem on installation process in the last github version. When I access to the site with a browser I can see in the url http://localhost/qa/install/license but I can see just the logo of QuickApps and nothing else.
No problem with the Tag version 1.0-RC1.zip

**Comment by quickapps** [comment]
https://github.com/QuickAppsCMS/QuickApps-CMS/commit/d92d82bcbe8c811644e3b3e433bfd485cb484acb

Thanks!
