### ISSUE TITLE
Changing role or disabling account for logged in users

### ISSUE THREAD

**Issue by ataylor32** [quickapps/cms#70]
Let's say that you wanted to change a user's role or disable their account. If you did either of these things while that user was logged in, it wouldn't take effect until that user logged out and back in (or until their session naturally expired). This isn't likely to be a big deal, but, in certain circumstances, it could be. Imagine if you wanted to disable their account because they were no longer trustworthy, yet they were logged in at the time.

**Comment by quickapps** [comment]
I think this will require to verify user's session against DB on every request.
Im working on it
