### ISSUE TITLE
Recaptcha and blackHoleHandler

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#71]
Hi Chris,

I updated the website online (and local) with latest sources, then I tried to insert a comment (with recaptcha) but I have this error message:

Duplicated content: Duplicate content detected!; it looks as though you've already sent that!

Without ReCaptcha is ok.
Then I tried to remove the new test comment and I had the same error page ...and I cannot remove the comment at all.

Thanks for your time

**Comment by Gabri** [comment]
It's ok reguarding the Recaptcha plugin.
The problem still exists when I try to delete comments, I have always the error page with:
Duplicated content: Duplicate content detected!; it looks as though you've already sent that!
I cannot remove comments at all

Thanks

**Comment by quickapps** [comment]
I've noticed that all the batch action lists (such nodes, users, etc) have this issue. 
This should solve problem on all the modules: b7ec77096becfb3d58558c2da38aea7ed10eda67

Thanks!

**Comment by Gabri** [comment]
Ok, it works fine!  :)
