### ISSUE TITLE
error notification on theme uninstallation

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#72]
Hi,

Probably not exactly an issue.

Today I was working on a new Theme.
I tried to uninstall an old version but I had a generic "Error uninstalling theme '<themename>'". I added some debug un uninstallation process and I discovered that a subfolder was not writable for apache user.
I have not found information about the kind of error. In the InstallerComponent I can see, for some kind of errors, filling the errors array like this:
$this->errors[] = __t('This module can not be uninstalled because some files/folder can not be deleted, please check the permissions.');
But I couldn't find any way to read this information (no on debug mode, no on log files).
I think the user should know, if there is an error, more information to solve it.
What do you think?

Bye

**Comment by quickapps** [comment]
Those empty quotes in the error message... It should be filled with the name of the theme.

```
Error uninstalling theme 'YourThemeName'
```

---

I'll add those error messages to the uninstall process output.
Also if debug > 0, error messages will be logged too.

**Comment by quickapps** [comment]
I think that should work.
But I still dont know the cause of those empty quotes :S

**Comment by Gabri** [comment]
Thank you very much, I'll try it this evening
