### ISSUE TITLE
breadcrumbs

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#73]
Hi,

I saw the "breadCrumb" function on LayoutHelper so I tried to use it.
There is an error on the function (or in the ctp) because the theme_breadcrumb.ctp is waiting for "$crumbs" and in the function is set "$breadcrumb".

There is another problem on this topic.
If I go to "Blog" and I click in an article (ie: /article/my-first-article.html) -> the variable is empty (and there is no item with "['MenuLink']" or something)

**Comment by quickapps** [comment]
Yes there is a typo on the variable name $crumbs->$breadcrumb.

But the second problem is not an issue, it's just the normal behavior.
Same as in Drupal, QuickApps's contents are non-hierarchical, means there is no way to know if a node is parent or child of another to automatically create those nice breadcrumbs.
That is why exists a "theme_breadcrumb.ctp" file: to allow you to create custom breadcrumbs based on your criterias.

For a better handling of breadcrumbs an external module would be required, that is why there two hook callbacks too:
- before_render_breadcrumb()
- after_render_breadcrumb()

## 

The only thing that I can do about the emty variable is: 
Same as Drupal:  add a "Home" link by default as the first element of the breadcrumb list.

## 

PS: Adding new elements to the breadcrumb list must be done using the _AppController::setCrumb()_

**Comment by Gabri** [comment]
Ok, I see. Thanks for the tip (AppController::setCrumb() ...I didn't know it)
Waiting to solve the typo  ;)

**Comment by quickapps** [comment]
I'm right now refactoring the all the breadcrumb system to make this easier to work with.

PS: check _QuickAppsComponent::setCrumb()_ docblock for [more info](http://api.quickappscms.org/1.1/source-class-QuickAppsComponent.html#574)

**Comment by quickapps** [comment]
I think this should work, check the _theme_breadcrumb.ctp_ element in Default theme for more information.

PS: I'll try to write some documentation about how breadcrumb system works

**Comment by Gabri** [comment]
If you go editing a block -> on top of the page you have:

Notice (8): Undefined offset: 1 [APP/Controller/Component/QuickAppsComponent.php, line 674]

**Comment by quickapps** [comment]
Fixed here:
06442a66fcd6225755c077286db69cd56d4f2baa
