### ISSUE TITLE
Uplodify

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#76]
Hi,

I have problem uploading file on a File Field.
I thought it was a permission problem, but not. I created manually the folder (on /webroot/files) specified on the Field settings (Do I need to create it manually or it creates automatically?)
Anyway, when I upload a file I get a "HTTP Error".
With Wireshark I found more details:
404 Not Found -> The requested URL /field_file/uploadify/upload/9/session_id:n3fmias5dis5atlcmgsf85gum7 was not found on this server.

I don't think is a my system configuration problem

Thanks

**Comment by quickapps** [comment]
I was totally unable to reproduce this issue (Latest RC2):
- My local installation works ok
- Demo site works ok too: http://demo.quickappscms.org

## 

Do I need to create it manually or it creates automatically?
You dont need to create it. The specified subdirectory is automatically created if not exists.

**Comment by Gabri** [comment]
I think I found the problem.
It happens on my local pc. All my installations in my local pc are done using virtualhosts, so for example to access this new website I go to "http://localhost/ial" or for stramaz "http://localhost/stramaz3".
The problem is that it tries to access "/field_file/uploadify/upload/9/..." and not "/ial/field_file/uploadify/upload/9/".
I found a similar problem on the search block, probably the QuickApps.doSearch(); (the action from is set correctly).
The strange thing is that stramaz installation (not updated to the last commits) works correctly

**Comment by quickapps** [comment]
Hmmm,
FieldFile uses the `QuickApps.settings.base_url` JS variable [when building the upload](https://github.com/QuickAppsCMS/QuickApps-CMS/blob/1.1/QuickApps/Plugin/Field/Fields/FieldFile/webroot/js/field_file.js#L19) URL. So I think that may be the problem.

You should have the following in your source code:

```
jQuery.extend(QuickApps.settings, {
     ....
    "base_url": "http://localhost/ial/",
```

But instead, for some reason, I think you have:

```
"base_url": "http://localhost/",
```

**Comment by Gabri** [comment]
Yes, verified: "http://localhost/"
Ops, a deja-vu ...like in Matrix  :)
I think the problem could be the 3 chars (ial) and the language prefix. We encountered a similar problem in the past, I remember...
QuickApps::strip_language_prefix probably strip "ial" as it was a language prefix:

jQuery.extend(QuickApps.settings, {
"version": "1.1-rc2",
"url": "http://localhost/ial/",
"base_url": "http://localhost/",
"domain": "localhost",
"locale": {"code":"eng","name":"English","native":"English","direction":"ltr","icon":"us.gif"}
});

**Comment by quickapps** [comment]
Oh! yes I remember. That is the cause:

https://github.com/QuickAppsCMS/QuickApps-CMS/blob/1.1/QuickApps/Controller/Component/QuickAppsComponent.php#L233

I think I can fix it

**Comment by Gabri** [comment]
Thanks, works fine!
