### ISSUE TITLE
upload file extension

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#77]
I add a File field and set the extension field to "kml".
When I upload the kml file it append ".txt" to the name of the file ...why?

**Comment by quickapps** [comment]
Oh, I think it's caused by the [Upload class](http://www.verot.net/php_class_upload.htm).

**Comment by Gabri** [comment]
I have the same rusult as before, always added a .txt at the end

**Comment by quickapps** [comment]
Hm, this should work:
7fb80a6f9c558b03d96b18a00de1ae6e5665dde5

But you should use it with caution. Now any ".php" wont be turned into ".php.txt", allowing to execute malicious code.

**Comment by Gabri** [comment]
Ok, it works; but if you think it could be riskful ...feel free to change it again as it was before!

**Comment by quickapps** [comment]
Nah, I think it's okay.
Site administrators should take care of this when assigning permissions.
