### ISSUE TITLE
Can't install new theme

### ISSUE THREAD

**Issue by kwunyeung** [quickapps/cms#8]
I can't upload and install new theme created by myself. It always gives me the following error.

Theme could not been installed:
Invalid package structure after unzip

I tried copying the default theme and changed the name with my theme name following the theme structure but I still can't install new themes.

**Comment by quickapps** [comment]
There is nothing wrong with the QA core. You are not correctly packaging your theme:
https://github.com/QuickAppsCMS/QuickApps-CMS/wiki/Creating-Installable-ZIP-packages

Check this example, it is just the `Default` theme renamed as `Example`:
http://www.mediafire.com/?52r3472336qrst9
(Also, verify that your QA core is up to date.)

P.S.: You can write me to my email and I'll be glad to assit you on creating your theme.

Regards!

**Comment by kwunyeung** [comment]
Thank you! I have just figured out why. It was due to the default compresser in OSX. I use Keka to compress the folder and it works.
