### ISSUE TITLE
Strange behavior on changing "display" settings on content types

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#81]
Hi,

I have a strange behavior on changing "display" settings on content types.
Latest sources. A new content type with different fields.
I choosed three display modes: Default, Full, List and saved.
Clicked on List and changing format of specific fields ...it save different settings that what I choosed (In List I set just hidden fields and unchecked 'hooktags'), 
After saving the format changement i have this notification (above display type buttons):
Notice (8): Undefined index: label [APP/Plugin/Node/View/Elements/toolbar-display.ctp, line 6]
And in the top of the page I have a new button (in addition to Default, Full and List) without lable that link to:
http://localhost/ial/admin/node/types/display/scheda_luogo (without indication of "/full" or "/list"...)

If I go back on List I can see that my previous changement on the format field was ...misunderstood  :)
I choosed hidden and now it says "link"

Thanks

**Comment by quickapps** [comment]
I'll take a look. It's caused by a previous commit.

**Comment by Gabri** [comment]
thanks, it works fine!
