### ISSUE TITLE
No puedo instalar/ I can't install

### ISSUE THREAD

**Issue by asiergil** [quickapps/cms#83]
== Spanish ===============================================================================
Hola, estoy intentando instalar el cms pero no lo consigo.
Subo todos los archivos a mi hosting y me salen varias frases en diferentes idiomas diciendo si quiero instalar la aplicacion. Le doy a la de mi idioma (Español) y me salta un error.

Tambien he probado a instalarlo con el index.install pero a la hora de darle a instalar, me salta este error:
QuickApps was not able to unzip the files it needs. (PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature)

Espero que me puedan ayudar. Saludos.

== English ================================================================================
Hello, I am trying to install the cms but it still fails.
I upload all the files to my hosting and I get several phrases in different languages ​​saying if I want to install the application. I give to my language (Spanish) and I skipped a mistake.

I've also tried to install it with the index.install but when installed giving me this error jump:
QuickApps was not able to unzip the files it needs. (PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature)

I hope you can help me. Greetings.

**Comment by quickapps** [comment]
Probably both problems are related to some server incompatibility.

---

I need more information about the first problem. What is the message you get after clicking "Spanish" installation?

For the second issue, googling a bit you will find that the problem can be solved by comenting this line in your _php.ini_:

```
; mbstring.func_overload = 7
```

---

Marking as invalid, as it's not a coding issue or bug

---

For this kind of problems I recommend you to open a new thread on [Google Group](https://groups.google.com/forum/?fromgroups#!forum/quickapps-cms) and paste the error message you are getting, so other people may assist you on solving your problem.
