### ISSUE TITLE
White screen of death on /admin

### ISSUE THREAD

**Issue by TobseTobse** [quickapps/cms#85]
Hi there,

I'm currently trying to program several modules (blocks) in QuickApps. Unhappily it happens quite often to me that I get a 0 byte result (empty page) with a 200 when I try to access /admin. I assume it has to do with the cache files, but I'm not sure if this is the case. Every time it happens I have to roll back DB and FS, which costs me a lot of time.

Do you have a quick solution at hand to solve this (e.g. a method to display more than 0 bytes but something like an error instead)? I've tried Configure::write('debug', 2) without success.

Is there maybe a CLI method to clean up the cache?

Thanks very much in advance for your answer.

**Comment by quickapps** [comment]
Hmm, sounds like a server incompatibility issue. Check your servers logs and try to find what is going on. (write permissions maybe?).

[Demo site](http://demo.quickappscms.org/) is uptodate and seem to work properly.

Also check this:
http://www.quickappscms.org/eng/page/quickapps-cli.html

---

I'll leave this ticket open for a while,
but for this kind of things (not highly related to coding) I recommend you to post your problem at here: https://groups.google.com/group/quickapps-cms

Best regards!

**Comment by TobseTobse** [comment]
Thanks very much for your quick response! I kept an eye on it for the past days and it hasn't happened anymore. I will try QA CLI those days.
