### ISSUE TITLE
wisiwig CK editor FieldableBehavior.php, line 205

### ISSUE THREAD

**Issue by romaing** [quickapps/cms#87]
Hi

I installed the Wysiwyg editor for textareas with parameter CK editor
when I go to new item I get this error
Notice (8): Undefined index: id [APP/Plugin/Field/Model/Behavior/FieldableBehavior.php, line 205]

best regard
romain

**Comment by quickapps** [comment]
Module fixed too at here:
https://github.com/QACMS-Modules/QACMS-Wysiwyg/commit/1c879476270762db577d51c54bb35205d26893e5
