### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by diit** [quickapps/cms#92]
For each method tried the application returns "An Internal Error Has Occurred.
Error: An Internal Error Has Occurred." and if the default installation method is used the application crashes with above error after inputting db details but also writes all the tables to the db.

Using wamp, meets all requirements.

**Comment by quickapps** [comment]
Could you please check your server logs?
So we can determine the causes

---

EDIT:
Also, did you try manual installation (using sql dumps)? this should always work

**Comment by diit** [comment]
the latest entry 

``` PHP
2013-07-10 19:58:26 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\wamp\www\Team4814_cms\0.0.1\Config\database.php, line 63]
2013-07-10 19:58:26 Error: [InternalErrorException] Internal Server Error
Request URL: /Team4814_cms/0.0.1/
Stack Trace:
#0 C:\wamp\www\Team4814_cms\0.0.1\QuickApps\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\wamp\www\Tea...', 63)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\wamp\www\Tea...', 63, Array)
#2 C:\wamp\www\Team4814_cms\0.0.1\QuickApps\Cake\Core\App.php(930): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\wamp\www\Tea...', 63, Array)
#3 C:\wamp\www\Team4814_cms\0.0.1\QuickApps\Cake\Core\App.php(903): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
```

and yes I tried manual, and it was able to write the db, but would return the same error when I tried to access the site.

Edit: I found the error, I should have checked the logs first, thanks for the quick reply.
