### ISSUE TITLE
error on adding content (that prevent saving it)

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#94]
QACMS from github of two weeks ago (more or less).
on backoffice, adding a new article, filling al fields and clicking on "Add Content" nothing happens. Chrome browser, in console I have this error every time I click on the button: "An invalid form control with name='data[MenuLink][link_title]' is not focusable".

On firefox clicking on the "Add Content" button it shows a tooltip saying "Please fill out this field." (but it is above the tab of the browser...). I filled all mandatory fields...

A small thing on firefox (v23): backoffice, in form editing (ie: adding an article) every block with radio buttons or checkboxes, the first input object is shown above the right place (over the text on legend tag)

**Comment by quickapps** [comment]
Yea, I remember the first issue (Menu link issue), But I think it's [already fixed](https://github.com/QuickAppsCMS/QuickApps-CMS/commit/fda9b5b0bb399cb256ccc6c9a650678939634c90), I was unable to reproduce this one neither.

The second one, just [fixed here](https://github.com/QuickAppsCMS/QuickApps-CMS/commit/52d716b751ebbaa629d27f9937f15f8458765ac9)

Best regards!

**Comment by Gabri** [comment]
Thanks Chris, super fast!
Everything works fine
