### ISSUE TITLE
Error on installing module via backoffice

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#95]
Hello,

This is the first time I tried to install a module directly from the backoffice (not downloading before the zip file from github).
When clickend on the install button (the module is Mediamanager) I had this error:

stream_socket_client(): Peer certificate CN=`*.github.com' did not match expected CN=`github.com' stream_socket_client(): Failed to enable crypto stream_socket_client(): unable to connect to ssl://codeload.github.com:443 (Unknown error)

Error: An Internal Error Has Occurred.

Go to home page

Stack Trace

```
APP/Cake/Network/CakeSocket.php line 273 → CakeSocket->connect()
APP/Cake/Network/Http/HttpSocket.php line 372 → CakeSocket->write(string)
APP/Cake/Network/Http/HttpSocket.php line 419 → HttpSocket->request(array)
APP/Cake/Network/Http/HttpSocket.php line 460 → HttpSocket->request(array)
APP/Controller/Component/InstallerComponent.php line 2015 → HttpSocket->get(array)
APP/Controller/Component/InstallerComponent.php line 104 → InstallerComponent->__downloadPackage(string, string)
APP/Plugin/System/Controller/ModulesController.php line 155 → InstallerComponent->install(array, array)
[internal function] → ModulesController->admin_install(string)
APP/Cake/Controller/Controller.php line 486 → ReflectionMethod->invokeArgs(ModulesController, array)
APP/Cake/Routing/Dispatcher.php line 187 → Controller->invokeAction(CakeRequest)
APP/Cake/Routing/Dispatcher.php line 162 → Dispatcher->_invoke(ModulesController, CakeRequest, CakeResponse)
ROOT/webroot/index.php line 110 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

P.s.: in the search form i wrote "media" and it didn't found anything, maybe it should be better to put some wildcards

**Comment by quickapps** [comment]
Hi,
Damn, GitHub upgrades...

Unfortunally this functionality is powered by GitHub API, which is
constantly changing.
Also, it's very limited. For instance wildchar are not allowed by its
search engine. Or for example, there is a limited amount of search request
you can perform from the same IP (QuickApps solves this by creating cache
copies of every search response).

I think I'll have to create a dedicated server for host every module/theme,
or migrate the system to another free service (I was thinking on CakePHP's
plugins repo).
If you have any idea or suggestion about this last, please feel free to
share :)

---

Anyway, this commit should fix the installation issues (for modules and
themes):

https://github.com/QuickAppsCMS/QuickApps-CMS/commit/62edc2bd756d06f6dff5978a125aef0fa4e2be1a

Regards!

2013/9/18 Gabri notifications@github.com

> Hello,
> 
> This is the first time I tried to install a module directly from the
> backoffice (not downloading before the zip file from github).
> When clickend on the install button (the module is Mediamanager) I had
> this error:
> 
> stream_socket_client(): Peer certificate CN=*.github.com' did not match
> expected CN=github.com' stream_socket_client(): Failed to enable crypto
> stream_socket_client(): unable to connect to ssl://codeload.github.com:443(Unknown error)
> 
> Error: An Internal Error Has Occurred.
> 
> Go to home page
> 
> Stack Trace
> 
> APP/Cake/Network/CakeSocket.php line 273 → CakeSocket->connect()
> APP/Cake/Network/Http/HttpSocket.php line 372 → CakeSocket->write(string)
> APP/Cake/Network/Http/HttpSocket.php line 419 → HttpSocket->request(array)
> APP/Cake/Network/Http/HttpSocket.php line 460 → HttpSocket->request(array)
> APP/Controller/Component/InstallerComponent.php line 2015 → HttpSocket->get(array)
> APP/Controller/Component/InstallerComponent.php line 104 → InstallerComponent->__downloadPackage(string, string)
> APP/Plugin/System/Controller/ModulesController.php line 155 → InstallerComponent->install(array, array)
> [internal function] → ModulesController->admin_install(string)
> APP/Cake/Controller/Controller.php line 486 → ReflectionMethod->invokeArgs(ModulesController, array)
> APP/Cake/Routing/Dispatcher.php line 187 → Controller->invokeAction(CakeRequest)
> APP/Cake/Routing/Dispatcher.php line 162 → Dispatcher->_invoke(ModulesController, CakeRequest, CakeResponse)
> ROOT/webroot/index.php line 110 → Dispatcher->dispatch(CakeRequest, CakeResponse)
> 
> P.s.: in the search form i wrote "media" and it didn't found anything,
> maybe it should be better to put some wildcards
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/QuickAppsCMS/QuickApps-CMS/issues/95
> .

## 

Christopher Castro.
Analista Programador Senior PHP/MySQL
Pamplona, España
QuickApps.es http://www.quickapps.eshttps://github.com/y2k2000/QuickApps
https://github.com/QuickAppsCMS/QuickApps-CMS

**Comment by Gabri** [comment]
Hi Chris,

Not sure... but maybe composer + packagist could be a way to solve this.
Composer is more for dependency management but maybe could be used also for this pouropose
