### ISSUE TITLE
Forbidden to access my website using QuickAppsCMS

### ISSUE THREAD

**Issue by AgungBS** [quickapps/cms#96]
I was uploaded QuickAppsCMS into my web server(web hosting) and I can not access my website. This is screen shoot of my website if I access it:
![untitled](https://f.cloud.github.com/assets/6167801/1731301/cb84c028-6301-11e3-9c46-b95b24c3676b.png)
So please give me the solution. Thanks.

**Comment by quickapps** [comment]
This has nothing to do with QA CMS,
The problem is your apache server, you must enable **mod_rewrite** to work as [described in the requirements](https://github.com/QuickAppsCMS/QuickApps-CMS#requirements)
