### ISSUE TITLE
Error before installing QuickApps-CMS

### ISSUE THREAD

**Issue by AgungBS** [quickapps/cms#97]
I want to install this CMS but i have an Error message, this is a screenshoot of the error message. 
![untitled](https://f.cloud.github.com/assets/6167801/1743694/ca090c58-6410-11e3-8f8d-5f8f062f7da6.png)
So please tell me the specific reason about the error, and how to resolve it?. Thank You.

**Comment by quickapps** [comment]
Well, the error message is really specific about it.
In your installation directory (./www) must be only your installation script

this is how your ./www/ should looks:
- ./www/
  - index.php -> this is the install script: http://www.quickappscms.org/files/installer/index.install

Try the GitHub based installation instead:
https://github.com/QuickAppsCMS/QuickApps-CMS#github-based-installer-recommended

---

PS: For this kind of problems please go to the oficial Google Group.
https://groups.google.com/group/quickapps-cms
