### ISSUE TITLE
composer support

### ISSUE THREAD

**Issue by dereuromark** [quickapps/cms#99]
Are you planning to provide composer support?
I was thinking about adding it to https://github.com/dereuromark/awesome-cakephp#cms-and-applications-built-on-cakephp

**Comment by quickapps** [comment]
Yes, actually I'm already working on version 2.0 of this CMS( powered by cake 3.0) which has composer support.
Latest stable version (1.x brach) has not composer support at the moment, but I have plans to provide this soon.

**Comment by dereuromark** [comment]
OK, I added the 2.0 branch (for Cake3.x) to the cake3 branch already :)

**Comment by quickapps** [comment]
Cool :+1: , 

thanks :)
